package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlAppStrategyResult;
import com.wealth.miniloan.entity.MlAppStrategyResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlAppStrategyResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int countByExample(MlAppStrategyResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int deleteByExample(MlAppStrategyResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int deleteByPrimaryKey(String appNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int insert(MlAppStrategyResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int insertSelective(MlAppStrategyResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	List<MlAppStrategyResult> selectByExample(MlAppStrategyResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	MlAppStrategyResult selectByPrimaryKey(String appNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int updateByExampleSelective(@Param("record") MlAppStrategyResult record,
			@Param("example") MlAppStrategyResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int updateByExample(@Param("record") MlAppStrategyResult record,
			@Param("example") MlAppStrategyResultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int updateByPrimaryKeySelective(MlAppStrategyResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_app_strategy_result
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	int updateByPrimaryKey(MlAppStrategyResult record);
}