package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlCapitalContrInfo;
import com.wealth.miniloan.entity.MlCapitalContrInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlCapitalContrInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int countByExample(MlCapitalContrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int deleteByExample(MlCapitalContrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int deleteByPrimaryKey(Long capitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int insert(MlCapitalContrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int insertSelective(MlCapitalContrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    List<MlCapitalContrInfo> selectByExample(MlCapitalContrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    MlCapitalContrInfo selectByPrimaryKey(Long capitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int updateByExampleSelective(@Param("record") MlCapitalContrInfo record, @Param("example") MlCapitalContrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int updateByExample(@Param("record") MlCapitalContrInfo record, @Param("example") MlCapitalContrInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int updateByPrimaryKeySelective(MlCapitalContrInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_capital_contr_info
     *
     * @mbggenerated Sun Nov 02 18:35:50 CST 2014
     */
    int updateByPrimaryKey(MlCapitalContrInfo record);
}