package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlCorpCustInfo;
import com.wealth.miniloan.entity.MlCorpCustInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlCorpCustInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int countByExample(MlCorpCustInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int deleteByExample(MlCorpCustInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int deleteByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int insert(MlCorpCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int insertSelective(MlCorpCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    List<MlCorpCustInfo> selectByExample(MlCorpCustInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    MlCorpCustInfo selectByPrimaryKey(String custNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") MlCorpCustInfo record, @Param("example") MlCorpCustInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int updateByExample(@Param("record") MlCorpCustInfo record, @Param("example") MlCorpCustInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(MlCorpCustInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    int updateByPrimaryKey(MlCorpCustInfo record);
}