package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlCorpAttach;
import com.wealth.miniloan.entity.MlCorpAttachExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlCorpAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int countByExample(MlCorpAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int deleteByExample(MlCorpAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int deleteByPrimaryKey(Long fileNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int insert(MlCorpAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int insertSelective(MlCorpAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    List<MlCorpAttach> selectByExample(MlCorpAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    MlCorpAttach selectByPrimaryKey(Long fileNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int updateByExampleSelective(@Param("record") MlCorpAttach record, @Param("example") MlCorpAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int updateByExample(@Param("record") MlCorpAttach record, @Param("example") MlCorpAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int updateByPrimaryKeySelective(MlCorpAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_corp_attach
     *
     * @mbggenerated Tue Sep 30 20:50:59 CST 2014
     */
    int updateByPrimaryKey(MlCorpAttach record);
}