package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlFraudCheckResult;
import com.wealth.miniloan.entity.MlFraudCheckResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlFraudCheckResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int countByExample(MlFraudCheckResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int deleteByExample(MlFraudCheckResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int deleteByPrimaryKey(Long checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int insert(MlFraudCheckResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int insertSelective(MlFraudCheckResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    List<MlFraudCheckResult> selectByExample(MlFraudCheckResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    MlFraudCheckResult selectByPrimaryKey(Long checkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int updateByExampleSelective(@Param("record") MlFraudCheckResult record, @Param("example") MlFraudCheckResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int updateByExample(@Param("record") MlFraudCheckResult record, @Param("example") MlFraudCheckResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int updateByPrimaryKeySelective(MlFraudCheckResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_fraud_check_result
     *
     * @mbggenerated Fri Oct 24 22:35:45 CST 2014
     */
    int updateByPrimaryKey(MlFraudCheckResult record);
}