package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlNaturalAttach;
import com.wealth.miniloan.entity.MlNaturalAttachExample;
import com.wealth.miniloan.entity.MlNaturalAttachKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlNaturalAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int countByExample(MlNaturalAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int deleteByExample(MlNaturalAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int deleteByPrimaryKey(MlNaturalAttachKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int insert(MlNaturalAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int insertSelective(MlNaturalAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    List<MlNaturalAttach> selectByExample(MlNaturalAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    MlNaturalAttach selectByPrimaryKey(MlNaturalAttachKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int updateByExampleSelective(@Param("record") MlNaturalAttach record, @Param("example") MlNaturalAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int updateByExample(@Param("record") MlNaturalAttach record, @Param("example") MlNaturalAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int updateByPrimaryKeySelective(MlNaturalAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_natural_attach
     *
     * @mbggenerated Sat Sep 27 17:30:29 CST 2014
     */
    int updateByPrimaryKey(MlNaturalAttach record);
}