package com.wealth.miniloan.dao;

import com.wealth.miniloan.entity.MlSysDecisionExclude;
import com.wealth.miniloan.entity.MlSysDecisionExcludeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MlSysDecisionExcludeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int countByExample(MlSysDecisionExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int deleteByExample(MlSysDecisionExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int deleteByPrimaryKey(Long excludeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int insert(MlSysDecisionExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int insertSelective(MlSysDecisionExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    List<MlSysDecisionExclude> selectByExample(MlSysDecisionExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    MlSysDecisionExclude selectByPrimaryKey(Long excludeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int updateByExampleSelective(@Param("record") MlSysDecisionExclude record, @Param("example") MlSysDecisionExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int updateByExample(@Param("record") MlSysDecisionExclude record, @Param("example") MlSysDecisionExcludeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int updateByPrimaryKeySelective(MlSysDecisionExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ml_sys_decision_exclude
     *
     * @mbggenerated Sat Oct 25 19:03:15 GMT+08:00 2014
     */
    int updateByPrimaryKey(MlSysDecisionExclude record);
}