package com.wealth.miniloan.entity;

import java.util.Date;

public class MlAppCheckResult {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.CHECK_ID
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private Long checkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.APP_NO
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private String appNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.CHECK_TYPE
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private String checkType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.CHECK_OBJ
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private String checkObj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.CHECK_RESULT
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private String checkResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.CHECK_DESC
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private String checkDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.APPROVER
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private Long approver;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_check_result.APPROVE_TIME
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	private Date approveTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.CHECK_ID
	 * @return  the value of ml_app_check_result.CHECK_ID
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public Long getCheckId() {
		return checkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.CHECK_ID
	 * @param checkId  the value for ml_app_check_result.CHECK_ID
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setCheckId(Long checkId) {
		this.checkId = checkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.APP_NO
	 * @return  the value of ml_app_check_result.APP_NO
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public String getAppNo() {
		return appNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.APP_NO
	 * @param appNo  the value for ml_app_check_result.APP_NO
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setAppNo(String appNo) {
		this.appNo = appNo == null ? null : appNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.CHECK_TYPE
	 * @return  the value of ml_app_check_result.CHECK_TYPE
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public String getCheckType() {
		return checkType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.CHECK_TYPE
	 * @param checkType  the value for ml_app_check_result.CHECK_TYPE
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setCheckType(String checkType) {
		this.checkType = checkType == null ? null : checkType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.CHECK_OBJ
	 * @return  the value of ml_app_check_result.CHECK_OBJ
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public String getCheckObj() {
		return checkObj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.CHECK_OBJ
	 * @param checkObj  the value for ml_app_check_result.CHECK_OBJ
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setCheckObj(String checkObj) {
		this.checkObj = checkObj == null ? null : checkObj.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.CHECK_RESULT
	 * @return  the value of ml_app_check_result.CHECK_RESULT
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public String getCheckResult() {
		return checkResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.CHECK_RESULT
	 * @param checkResult  the value for ml_app_check_result.CHECK_RESULT
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setCheckResult(String checkResult) {
		this.checkResult = checkResult == null ? null : checkResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.CHECK_DESC
	 * @return  the value of ml_app_check_result.CHECK_DESC
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public String getCheckDesc() {
		return checkDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.CHECK_DESC
	 * @param checkDesc  the value for ml_app_check_result.CHECK_DESC
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setCheckDesc(String checkDesc) {
		this.checkDesc = checkDesc == null ? null : checkDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.APPROVER
	 * @return  the value of ml_app_check_result.APPROVER
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public Long getApprover() {
		return approver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.APPROVER
	 * @param approver  the value for ml_app_check_result.APPROVER
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setApprover(Long approver) {
		this.approver = approver;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_check_result.APPROVE_TIME
	 * @return  the value of ml_app_check_result.APPROVE_TIME
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public Date getApproveTime() {
		return approveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_check_result.APPROVE_TIME
	 * @param approveTime  the value for ml_app_check_result.APPROVE_TIME
	 * @mbggenerated  Fri Oct 03 15:48:55 CST 2014
	 */
	public void setApproveTime(Date approveTime) {
		this.approveTime = approveTime;
	}
}