package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MlAppStrategyResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.APP_NO
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private String appNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.SYS_RESULT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private String sysResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.SYS_REASON
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private String sysReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.SYS_LOAN_LIMIT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private BigDecimal sysLoanLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.SYS_LOAN_PRODUCT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private String sysLoanProduct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_app_strategy_result.SYS_DECISION_TIME
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    private Date sysDecisionTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.APP_NO
     *
     * @return the value of ml_app_strategy_result.APP_NO
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public String getAppNo() {
        return appNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.APP_NO
     *
     * @param appNo the value for ml_app_strategy_result.APP_NO
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setAppNo(String appNo) {
        this.appNo = appNo == null ? null : appNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.SYS_RESULT
     *
     * @return the value of ml_app_strategy_result.SYS_RESULT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public String getSysResult() {
        return sysResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.SYS_RESULT
     *
     * @param sysResult the value for ml_app_strategy_result.SYS_RESULT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setSysResult(String sysResult) {
        this.sysResult = sysResult == null ? null : sysResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.SYS_REASON
     *
     * @return the value of ml_app_strategy_result.SYS_REASON
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public String getSysReason() {
        return sysReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.SYS_REASON
     *
     * @param sysReason the value for ml_app_strategy_result.SYS_REASON
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setSysReason(String sysReason) {
        this.sysReason = sysReason == null ? null : sysReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.SYS_LOAN_LIMIT
     *
     * @return the value of ml_app_strategy_result.SYS_LOAN_LIMIT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public BigDecimal getSysLoanLimit() {
        return sysLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.SYS_LOAN_LIMIT
     *
     * @param sysLoanLimit the value for ml_app_strategy_result.SYS_LOAN_LIMIT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setSysLoanLimit(BigDecimal sysLoanLimit) {
        this.sysLoanLimit = sysLoanLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.SYS_LOAN_PRODUCT
     *
     * @return the value of ml_app_strategy_result.SYS_LOAN_PRODUCT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public String getSysLoanProduct() {
        return sysLoanProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.SYS_LOAN_PRODUCT
     *
     * @param sysLoanProduct the value for ml_app_strategy_result.SYS_LOAN_PRODUCT
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setSysLoanProduct(String sysLoanProduct) {
        this.sysLoanProduct = sysLoanProduct == null ? null : sysLoanProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_app_strategy_result.SYS_DECISION_TIME
     *
     * @return the value of ml_app_strategy_result.SYS_DECISION_TIME
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public Date getSysDecisionTime() {
        return sysDecisionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_app_strategy_result.SYS_DECISION_TIME
     *
     * @param sysDecisionTime the value for ml_app_strategy_result.SYS_DECISION_TIME
     *
     * @mbggenerated Wed Oct 01 16:15:12 CST 2014
     */
    public void setSysDecisionTime(Date sysDecisionTime) {
        this.sysDecisionTime = sysDecisionTime;
    }
}