package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MlAppStrategyResult {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.APP_NO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String appNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.FRAUD_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String fraudCheckResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.BASE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String baseCheckResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.RELEVANCE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String relevanceCheckResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.CROSS_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String crossCheckResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.LOAN_APP_AMOUNT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal loanAppAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.BASE_LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal baseLoanRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.HAS_CREDIT_INFO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String hasCreditInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.PAST_DUE_TIMES
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private Integer pastDueTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private Integer highestDelinquencyCycle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal amountOfDelinquency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.AGE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.MARRIAGE_STATUS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String marriageStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.EDU_LVL
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String eduLvl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.WORK_YEARS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal workYears;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.ANNUAL_INCOME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal annualIncome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.MORT_RATIO_OF_LOAN
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal mortRatioOfLoan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.SCORE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.SYS_DEC_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String sysDecResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.LOAN_LIMIT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal loanLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private BigDecimal loanRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.REASON_CODE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String reasonCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.REASON_DESC
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private String reasonDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_app_strategy_result.DECISION_TIME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	private Date decisionTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.APP_NO
	 * @return  the value of ml_app_strategy_result.APP_NO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getAppNo() {
		return appNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.APP_NO
	 * @param appNo  the value for ml_app_strategy_result.APP_NO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setAppNo(String appNo) {
		this.appNo = appNo == null ? null : appNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.FRAUD_CHECK_RESULT
	 * @return  the value of ml_app_strategy_result.FRAUD_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getFraudCheckResult() {
		return fraudCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.FRAUD_CHECK_RESULT
	 * @param fraudCheckResult  the value for ml_app_strategy_result.FRAUD_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setFraudCheckResult(String fraudCheckResult) {
		this.fraudCheckResult = fraudCheckResult == null ? null
				: fraudCheckResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.BASE_CHECK_RESULT
	 * @return  the value of ml_app_strategy_result.BASE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getBaseCheckResult() {
		return baseCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.BASE_CHECK_RESULT
	 * @param baseCheckResult  the value for ml_app_strategy_result.BASE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setBaseCheckResult(String baseCheckResult) {
		this.baseCheckResult = baseCheckResult == null ? null : baseCheckResult
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.RELEVANCE_CHECK_RESULT
	 * @return  the value of ml_app_strategy_result.RELEVANCE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getRelevanceCheckResult() {
		return relevanceCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.RELEVANCE_CHECK_RESULT
	 * @param relevanceCheckResult  the value for ml_app_strategy_result.RELEVANCE_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setRelevanceCheckResult(String relevanceCheckResult) {
		this.relevanceCheckResult = relevanceCheckResult == null ? null
				: relevanceCheckResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.CROSS_CHECK_RESULT
	 * @return  the value of ml_app_strategy_result.CROSS_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getCrossCheckResult() {
		return crossCheckResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.CROSS_CHECK_RESULT
	 * @param crossCheckResult  the value for ml_app_strategy_result.CROSS_CHECK_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setCrossCheckResult(String crossCheckResult) {
		this.crossCheckResult = crossCheckResult == null ? null
				: crossCheckResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.LOAN_APP_AMOUNT
	 * @return  the value of ml_app_strategy_result.LOAN_APP_AMOUNT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getLoanAppAmount() {
		return loanAppAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.LOAN_APP_AMOUNT
	 * @param loanAppAmount  the value for ml_app_strategy_result.LOAN_APP_AMOUNT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setLoanAppAmount(BigDecimal loanAppAmount) {
		this.loanAppAmount = loanAppAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.BASE_LOAN_RATE
	 * @return  the value of ml_app_strategy_result.BASE_LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getBaseLoanRate() {
		return baseLoanRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.BASE_LOAN_RATE
	 * @param baseLoanRate  the value for ml_app_strategy_result.BASE_LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setBaseLoanRate(BigDecimal baseLoanRate) {
		this.baseLoanRate = baseLoanRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.HAS_CREDIT_INFO
	 * @return  the value of ml_app_strategy_result.HAS_CREDIT_INFO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getHasCreditInfo() {
		return hasCreditInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.HAS_CREDIT_INFO
	 * @param hasCreditInfo  the value for ml_app_strategy_result.HAS_CREDIT_INFO
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setHasCreditInfo(String hasCreditInfo) {
		this.hasCreditInfo = hasCreditInfo == null ? null : hasCreditInfo
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.PAST_DUE_TIMES
	 * @return  the value of ml_app_strategy_result.PAST_DUE_TIMES
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public Integer getPastDueTimes() {
		return pastDueTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.PAST_DUE_TIMES
	 * @param pastDueTimes  the value for ml_app_strategy_result.PAST_DUE_TIMES
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setPastDueTimes(Integer pastDueTimes) {
		this.pastDueTimes = pastDueTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.HIGHEST_DELINQUENCY_CYCLE
	 * @return  the value of ml_app_strategy_result.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public Integer getHighestDelinquencyCycle() {
		return highestDelinquencyCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.HIGHEST_DELINQUENCY_CYCLE
	 * @param highestDelinquencyCycle  the value for ml_app_strategy_result.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setHighestDelinquencyCycle(Integer highestDelinquencyCycle) {
		this.highestDelinquencyCycle = highestDelinquencyCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.AMOUNT_OF_DELINQUENCY
	 * @return  the value of ml_app_strategy_result.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getAmountOfDelinquency() {
		return amountOfDelinquency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.AMOUNT_OF_DELINQUENCY
	 * @param amountOfDelinquency  the value for ml_app_strategy_result.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setAmountOfDelinquency(BigDecimal amountOfDelinquency) {
		this.amountOfDelinquency = amountOfDelinquency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.AGE
	 * @return  the value of ml_app_strategy_result.AGE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.AGE
	 * @param age  the value for ml_app_strategy_result.AGE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setAge(BigDecimal age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.MARRIAGE_STATUS
	 * @return  the value of ml_app_strategy_result.MARRIAGE_STATUS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getMarriageStatus() {
		return marriageStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.MARRIAGE_STATUS
	 * @param marriageStatus  the value for ml_app_strategy_result.MARRIAGE_STATUS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setMarriageStatus(String marriageStatus) {
		this.marriageStatus = marriageStatus == null ? null : marriageStatus
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.EDU_LVL
	 * @return  the value of ml_app_strategy_result.EDU_LVL
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getEduLvl() {
		return eduLvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.EDU_LVL
	 * @param eduLvl  the value for ml_app_strategy_result.EDU_LVL
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setEduLvl(String eduLvl) {
		this.eduLvl = eduLvl == null ? null : eduLvl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.WORK_YEARS
	 * @return  the value of ml_app_strategy_result.WORK_YEARS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getWorkYears() {
		return workYears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.WORK_YEARS
	 * @param workYears  the value for ml_app_strategy_result.WORK_YEARS
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setWorkYears(BigDecimal workYears) {
		this.workYears = workYears;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.ANNUAL_INCOME
	 * @return  the value of ml_app_strategy_result.ANNUAL_INCOME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getAnnualIncome() {
		return annualIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.ANNUAL_INCOME
	 * @param annualIncome  the value for ml_app_strategy_result.ANNUAL_INCOME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setAnnualIncome(BigDecimal annualIncome) {
		this.annualIncome = annualIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.MORT_RATIO_OF_LOAN
	 * @return  the value of ml_app_strategy_result.MORT_RATIO_OF_LOAN
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getMortRatioOfLoan() {
		return mortRatioOfLoan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.MORT_RATIO_OF_LOAN
	 * @param mortRatioOfLoan  the value for ml_app_strategy_result.MORT_RATIO_OF_LOAN
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setMortRatioOfLoan(BigDecimal mortRatioOfLoan) {
		this.mortRatioOfLoan = mortRatioOfLoan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.SCORE
	 * @return  the value of ml_app_strategy_result.SCORE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.SCORE
	 * @param score  the value for ml_app_strategy_result.SCORE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.SYS_DEC_RESULT
	 * @return  the value of ml_app_strategy_result.SYS_DEC_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getSysDecResult() {
		return sysDecResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.SYS_DEC_RESULT
	 * @param sysDecResult  the value for ml_app_strategy_result.SYS_DEC_RESULT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setSysDecResult(String sysDecResult) {
		this.sysDecResult = sysDecResult == null ? null : sysDecResult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.LOAN_LIMIT
	 * @return  the value of ml_app_strategy_result.LOAN_LIMIT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getLoanLimit() {
		return loanLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.LOAN_LIMIT
	 * @param loanLimit  the value for ml_app_strategy_result.LOAN_LIMIT
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setLoanLimit(BigDecimal loanLimit) {
		this.loanLimit = loanLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.LOAN_RATE
	 * @return  the value of ml_app_strategy_result.LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public BigDecimal getLoanRate() {
		return loanRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.LOAN_RATE
	 * @param loanRate  the value for ml_app_strategy_result.LOAN_RATE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setLoanRate(BigDecimal loanRate) {
		this.loanRate = loanRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.REASON_CODE
	 * @return  the value of ml_app_strategy_result.REASON_CODE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getReasonCode() {
		return reasonCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.REASON_CODE
	 * @param reasonCode  the value for ml_app_strategy_result.REASON_CODE
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode == null ? null : reasonCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.REASON_DESC
	 * @return  the value of ml_app_strategy_result.REASON_DESC
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public String getReasonDesc() {
		return reasonDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.REASON_DESC
	 * @param reasonDesc  the value for ml_app_strategy_result.REASON_DESC
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setReasonDesc(String reasonDesc) {
		this.reasonDesc = reasonDesc == null ? null : reasonDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_app_strategy_result.DECISION_TIME
	 * @return  the value of ml_app_strategy_result.DECISION_TIME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public Date getDecisionTime() {
		return decisionTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_app_strategy_result.DECISION_TIME
	 * @param decisionTime  the value for ml_app_strategy_result.DECISION_TIME
	 * @mbggenerated  Sat Oct 25 21:44:07 GMT+08:00 2014
	 */
	public void setDecisionTime(Date decisionTime) {
		this.decisionTime = decisionTime;
	}
}