package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MlBorrower {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.borrower_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private Long borrowerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.cust_code
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String custCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.cust_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String custType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.gender
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.birth_day
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.nationality
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.education
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.politics
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String politics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String idIssuanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String idExpirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mobilePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mobilePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String fixedPhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String fixedPhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String wechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.car_brand
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String carBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.car_number
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String carNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.car_status
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String carStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.car_buy_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String carBuyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String jobCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String jobDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String jobDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String jobBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String companyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String companyPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String homeAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String homePost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.housing
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String housing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.house_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String houseBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateIdIssuanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateIdExpirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateJobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateJobCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateJobDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateJobDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateJobBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateCompanyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateCompanyPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateMobilePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateMobilePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateFixedPhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateFixedPhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.mate_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String mateWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.has_guarantor
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String hasGuarantor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.guarantor_cust_code1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String guarantorCustCode1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.guarantor_cust_code2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String guarantorCustCode2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.guarantor_cust_code3
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String guarantorCustCode3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactCustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactIdIssuanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactIdExpirationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactJobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactJobCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactJobDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactJobDuty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactJobBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactCompanyAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactCompanyPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactHomeAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactHomePost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactMobilePhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactMobilePhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactFixedPhone1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactFixedPhone2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.contact_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String contactWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.cretid_limit
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private BigDecimal cretidLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.credit_deadline
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String creditDeadline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.is_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String isPassDue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.longest_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String longestPassDue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.bank
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.account_outlet
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String accountOutlet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.account
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.enter_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private Long enterUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.check_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private Long checkUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.last_update_time
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.last_update_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private Long lastUpdateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_borrower.marketing_staff
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    private String marketingStaff;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.borrower_id
     *
     * @return the value of ml_borrower.borrower_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public Long getBorrowerId() {
        return borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.borrower_id
     *
     * @param borrowerId the value for ml_borrower.borrower_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setBorrowerId(Long borrowerId) {
        this.borrowerId = borrowerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.cust_code
     *
     * @return the value of ml_borrower.cust_code
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCustCode() {
        return custCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.cust_code
     *
     * @param custCode the value for ml_borrower.cust_code
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCustCode(String custCode) {
        this.custCode = custCode == null ? null : custCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.cust_type
     *
     * @return the value of ml_borrower.cust_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCustType() {
        return custType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.cust_type
     *
     * @param custType the value for ml_borrower.cust_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCustType(String custType) {
        this.custType = custType == null ? null : custType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.name
     *
     * @return the value of ml_borrower.name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.name
     *
     * @param name the value for ml_borrower.name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.id_type
     *
     * @return the value of ml_borrower.id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.id_type
     *
     * @param idType the value for ml_borrower.id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.cust_id
     *
     * @return the value of ml_borrower.cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.cust_id
     *
     * @param custId the value for ml_borrower.cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.gender
     *
     * @return the value of ml_borrower.gender
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.gender
     *
     * @param gender the value for ml_borrower.gender
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.birth_day
     *
     * @return the value of ml_borrower.birth_day
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.birth_day
     *
     * @param birthDay the value for ml_borrower.birth_day
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay == null ? null : birthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.nationality
     *
     * @return the value of ml_borrower.nationality
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.nationality
     *
     * @param nationality the value for ml_borrower.nationality
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.education
     *
     * @return the value of ml_borrower.education
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.education
     *
     * @param education the value for ml_borrower.education
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.politics
     *
     * @return the value of ml_borrower.politics
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getPolitics() {
        return politics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.politics
     *
     * @param politics the value for ml_borrower.politics
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setPolitics(String politics) {
        this.politics = politics == null ? null : politics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.id_issuance_date
     *
     * @return the value of ml_borrower.id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getIdIssuanceDate() {
        return idIssuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.id_issuance_date
     *
     * @param idIssuanceDate the value for ml_borrower.id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setIdIssuanceDate(String idIssuanceDate) {
        this.idIssuanceDate = idIssuanceDate == null ? null : idIssuanceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.id_expiration_date
     *
     * @return the value of ml_borrower.id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getIdExpirationDate() {
        return idExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.id_expiration_date
     *
     * @param idExpirationDate the value for ml_borrower.id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setIdExpirationDate(String idExpirationDate) {
        this.idExpirationDate = idExpirationDate == null ? null : idExpirationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mobile_phone1
     *
     * @return the value of ml_borrower.mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMobilePhone1() {
        return mobilePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mobile_phone1
     *
     * @param mobilePhone1 the value for ml_borrower.mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMobilePhone1(String mobilePhone1) {
        this.mobilePhone1 = mobilePhone1 == null ? null : mobilePhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mobile_phone2
     *
     * @return the value of ml_borrower.mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMobilePhone2() {
        return mobilePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mobile_phone2
     *
     * @param mobilePhone2 the value for ml_borrower.mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMobilePhone2(String mobilePhone2) {
        this.mobilePhone2 = mobilePhone2 == null ? null : mobilePhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.fixed_phone1
     *
     * @return the value of ml_borrower.fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getFixedPhone1() {
        return fixedPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.fixed_phone1
     *
     * @param fixedPhone1 the value for ml_borrower.fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setFixedPhone1(String fixedPhone1) {
        this.fixedPhone1 = fixedPhone1 == null ? null : fixedPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.fixed_phone2
     *
     * @return the value of ml_borrower.fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getFixedPhone2() {
        return fixedPhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.fixed_phone2
     *
     * @param fixedPhone2 the value for ml_borrower.fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setFixedPhone2(String fixedPhone2) {
        this.fixedPhone2 = fixedPhone2 == null ? null : fixedPhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.email
     *
     * @return the value of ml_borrower.email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.email
     *
     * @param email the value for ml_borrower.email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.qq
     *
     * @return the value of ml_borrower.qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.qq
     *
     * @param qq the value for ml_borrower.qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.wechat
     *
     * @return the value of ml_borrower.wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.wechat
     *
     * @param wechat the value for ml_borrower.wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.car_brand
     *
     * @return the value of ml_borrower.car_brand
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.car_brand
     *
     * @param carBrand the value for ml_borrower.car_brand
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.car_number
     *
     * @return the value of ml_borrower.car_number
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.car_number
     *
     * @param carNumber the value for ml_borrower.car_number
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.car_status
     *
     * @return the value of ml_borrower.car_status
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCarStatus() {
        return carStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.car_status
     *
     * @param carStatus the value for ml_borrower.car_status
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCarStatus(String carStatus) {
        this.carStatus = carStatus == null ? null : carStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.car_buy_date
     *
     * @return the value of ml_borrower.car_buy_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCarBuyDate() {
        return carBuyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.car_buy_date
     *
     * @param carBuyDate the value for ml_borrower.car_buy_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCarBuyDate(String carBuyDate) {
        this.carBuyDate = carBuyDate == null ? null : carBuyDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.job_type
     *
     * @return the value of ml_borrower.job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.job_type
     *
     * @param jobType the value for ml_borrower.job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setJobType(String jobType) {
        this.jobType = jobType == null ? null : jobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.job_company
     *
     * @return the value of ml_borrower.job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getJobCompany() {
        return jobCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.job_company
     *
     * @param jobCompany the value for ml_borrower.job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setJobCompany(String jobCompany) {
        this.jobCompany = jobCompany == null ? null : jobCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.job_dept
     *
     * @return the value of ml_borrower.job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getJobDept() {
        return jobDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.job_dept
     *
     * @param jobDept the value for ml_borrower.job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setJobDept(String jobDept) {
        this.jobDept = jobDept == null ? null : jobDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.job_duty
     *
     * @return the value of ml_borrower.job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getJobDuty() {
        return jobDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.job_duty
     *
     * @param jobDuty the value for ml_borrower.job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setJobDuty(String jobDuty) {
        this.jobDuty = jobDuty == null ? null : jobDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.job_begin_date
     *
     * @return the value of ml_borrower.job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getJobBeginDate() {
        return jobBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.job_begin_date
     *
     * @param jobBeginDate the value for ml_borrower.job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setJobBeginDate(String jobBeginDate) {
        this.jobBeginDate = jobBeginDate == null ? null : jobBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.company_addr
     *
     * @return the value of ml_borrower.company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCompanyAddr() {
        return companyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.company_addr
     *
     * @param companyAddr the value for ml_borrower.company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCompanyAddr(String companyAddr) {
        this.companyAddr = companyAddr == null ? null : companyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.company_post
     *
     * @return the value of ml_borrower.company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCompanyPost() {
        return companyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.company_post
     *
     * @param companyPost the value for ml_borrower.company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCompanyPost(String companyPost) {
        this.companyPost = companyPost == null ? null : companyPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.home_addr
     *
     * @return the value of ml_borrower.home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getHomeAddr() {
        return homeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.home_addr
     *
     * @param homeAddr the value for ml_borrower.home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setHomeAddr(String homeAddr) {
        this.homeAddr = homeAddr == null ? null : homeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.home_post
     *
     * @return the value of ml_borrower.home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getHomePost() {
        return homePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.home_post
     *
     * @param homePost the value for ml_borrower.home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setHomePost(String homePost) {
        this.homePost = homePost == null ? null : homePost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.housing
     *
     * @return the value of ml_borrower.housing
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getHousing() {
        return housing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.housing
     *
     * @param housing the value for ml_borrower.housing
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setHousing(String housing) {
        this.housing = housing == null ? null : housing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.house_begin_date
     *
     * @return the value of ml_borrower.house_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getHouseBeginDate() {
        return houseBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.house_begin_date
     *
     * @param houseBeginDate the value for ml_borrower.house_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setHouseBeginDate(String houseBeginDate) {
        this.houseBeginDate = houseBeginDate == null ? null : houseBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_name
     *
     * @return the value of ml_borrower.mate_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateName() {
        return mateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_name
     *
     * @param mateName the value for ml_borrower.mate_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateName(String mateName) {
        this.mateName = mateName == null ? null : mateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_id_type
     *
     * @return the value of ml_borrower.mate_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateIdType() {
        return mateIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_id_type
     *
     * @param mateIdType the value for ml_borrower.mate_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateIdType(String mateIdType) {
        this.mateIdType = mateIdType == null ? null : mateIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_cust_id
     *
     * @return the value of ml_borrower.mate_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateCustId() {
        return mateCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_cust_id
     *
     * @param mateCustId the value for ml_borrower.mate_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateCustId(String mateCustId) {
        this.mateCustId = mateCustId == null ? null : mateCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_id_issuance_date
     *
     * @return the value of ml_borrower.mate_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateIdIssuanceDate() {
        return mateIdIssuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_id_issuance_date
     *
     * @param mateIdIssuanceDate the value for ml_borrower.mate_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateIdIssuanceDate(String mateIdIssuanceDate) {
        this.mateIdIssuanceDate = mateIdIssuanceDate == null ? null : mateIdIssuanceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_id_expiration_date
     *
     * @return the value of ml_borrower.mate_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateIdExpirationDate() {
        return mateIdExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_id_expiration_date
     *
     * @param mateIdExpirationDate the value for ml_borrower.mate_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateIdExpirationDate(String mateIdExpirationDate) {
        this.mateIdExpirationDate = mateIdExpirationDate == null ? null : mateIdExpirationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_job_type
     *
     * @return the value of ml_borrower.mate_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateJobType() {
        return mateJobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_job_type
     *
     * @param mateJobType the value for ml_borrower.mate_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateJobType(String mateJobType) {
        this.mateJobType = mateJobType == null ? null : mateJobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_job_company
     *
     * @return the value of ml_borrower.mate_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateJobCompany() {
        return mateJobCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_job_company
     *
     * @param mateJobCompany the value for ml_borrower.mate_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateJobCompany(String mateJobCompany) {
        this.mateJobCompany = mateJobCompany == null ? null : mateJobCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_job_dept
     *
     * @return the value of ml_borrower.mate_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateJobDept() {
        return mateJobDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_job_dept
     *
     * @param mateJobDept the value for ml_borrower.mate_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateJobDept(String mateJobDept) {
        this.mateJobDept = mateJobDept == null ? null : mateJobDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_job_duty
     *
     * @return the value of ml_borrower.mate_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateJobDuty() {
        return mateJobDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_job_duty
     *
     * @param mateJobDuty the value for ml_borrower.mate_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateJobDuty(String mateJobDuty) {
        this.mateJobDuty = mateJobDuty == null ? null : mateJobDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_job_begin_date
     *
     * @return the value of ml_borrower.mate_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateJobBeginDate() {
        return mateJobBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_job_begin_date
     *
     * @param mateJobBeginDate the value for ml_borrower.mate_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateJobBeginDate(String mateJobBeginDate) {
        this.mateJobBeginDate = mateJobBeginDate == null ? null : mateJobBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_company_addr
     *
     * @return the value of ml_borrower.mate_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateCompanyAddr() {
        return mateCompanyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_company_addr
     *
     * @param mateCompanyAddr the value for ml_borrower.mate_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateCompanyAddr(String mateCompanyAddr) {
        this.mateCompanyAddr = mateCompanyAddr == null ? null : mateCompanyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_company_post
     *
     * @return the value of ml_borrower.mate_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateCompanyPost() {
        return mateCompanyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_company_post
     *
     * @param mateCompanyPost the value for ml_borrower.mate_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateCompanyPost(String mateCompanyPost) {
        this.mateCompanyPost = mateCompanyPost == null ? null : mateCompanyPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_mobile_phone1
     *
     * @return the value of ml_borrower.mate_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateMobilePhone1() {
        return mateMobilePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_mobile_phone1
     *
     * @param mateMobilePhone1 the value for ml_borrower.mate_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateMobilePhone1(String mateMobilePhone1) {
        this.mateMobilePhone1 = mateMobilePhone1 == null ? null : mateMobilePhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_mobile_phone2
     *
     * @return the value of ml_borrower.mate_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateMobilePhone2() {
        return mateMobilePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_mobile_phone2
     *
     * @param mateMobilePhone2 the value for ml_borrower.mate_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateMobilePhone2(String mateMobilePhone2) {
        this.mateMobilePhone2 = mateMobilePhone2 == null ? null : mateMobilePhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_fixed_phone1
     *
     * @return the value of ml_borrower.mate_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateFixedPhone1() {
        return mateFixedPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_fixed_phone1
     *
     * @param mateFixedPhone1 the value for ml_borrower.mate_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateFixedPhone1(String mateFixedPhone1) {
        this.mateFixedPhone1 = mateFixedPhone1 == null ? null : mateFixedPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_fixed_phone2
     *
     * @return the value of ml_borrower.mate_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateFixedPhone2() {
        return mateFixedPhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_fixed_phone2
     *
     * @param mateFixedPhone2 the value for ml_borrower.mate_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateFixedPhone2(String mateFixedPhone2) {
        this.mateFixedPhone2 = mateFixedPhone2 == null ? null : mateFixedPhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_email
     *
     * @return the value of ml_borrower.mate_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateEmail() {
        return mateEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_email
     *
     * @param mateEmail the value for ml_borrower.mate_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateEmail(String mateEmail) {
        this.mateEmail = mateEmail == null ? null : mateEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_qq
     *
     * @return the value of ml_borrower.mate_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateQq() {
        return mateQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_qq
     *
     * @param mateQq the value for ml_borrower.mate_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateQq(String mateQq) {
        this.mateQq = mateQq == null ? null : mateQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.mate_wechat
     *
     * @return the value of ml_borrower.mate_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMateWechat() {
        return mateWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.mate_wechat
     *
     * @param mateWechat the value for ml_borrower.mate_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMateWechat(String mateWechat) {
        this.mateWechat = mateWechat == null ? null : mateWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.has_guarantor
     *
     * @return the value of ml_borrower.has_guarantor
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getHasGuarantor() {
        return hasGuarantor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.has_guarantor
     *
     * @param hasGuarantor the value for ml_borrower.has_guarantor
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setHasGuarantor(String hasGuarantor) {
        this.hasGuarantor = hasGuarantor == null ? null : hasGuarantor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.guarantor_cust_code1
     *
     * @return the value of ml_borrower.guarantor_cust_code1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getGuarantorCustCode1() {
        return guarantorCustCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.guarantor_cust_code1
     *
     * @param guarantorCustCode1 the value for ml_borrower.guarantor_cust_code1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setGuarantorCustCode1(String guarantorCustCode1) {
        this.guarantorCustCode1 = guarantorCustCode1 == null ? null : guarantorCustCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.guarantor_cust_code2
     *
     * @return the value of ml_borrower.guarantor_cust_code2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getGuarantorCustCode2() {
        return guarantorCustCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.guarantor_cust_code2
     *
     * @param guarantorCustCode2 the value for ml_borrower.guarantor_cust_code2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setGuarantorCustCode2(String guarantorCustCode2) {
        this.guarantorCustCode2 = guarantorCustCode2 == null ? null : guarantorCustCode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.guarantor_cust_code3
     *
     * @return the value of ml_borrower.guarantor_cust_code3
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getGuarantorCustCode3() {
        return guarantorCustCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.guarantor_cust_code3
     *
     * @param guarantorCustCode3 the value for ml_borrower.guarantor_cust_code3
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setGuarantorCustCode3(String guarantorCustCode3) {
        this.guarantorCustCode3 = guarantorCustCode3 == null ? null : guarantorCustCode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_name
     *
     * @return the value of ml_borrower.contact_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_name
     *
     * @param contactName the value for ml_borrower.contact_name
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_id_type
     *
     * @return the value of ml_borrower.contact_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactIdType() {
        return contactIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_id_type
     *
     * @param contactIdType the value for ml_borrower.contact_id_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactIdType(String contactIdType) {
        this.contactIdType = contactIdType == null ? null : contactIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_cust_id
     *
     * @return the value of ml_borrower.contact_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactCustId() {
        return contactCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_cust_id
     *
     * @param contactCustId the value for ml_borrower.contact_cust_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactCustId(String contactCustId) {
        this.contactCustId = contactCustId == null ? null : contactCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_id_issuance_date
     *
     * @return the value of ml_borrower.contact_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactIdIssuanceDate() {
        return contactIdIssuanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_id_issuance_date
     *
     * @param contactIdIssuanceDate the value for ml_borrower.contact_id_issuance_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactIdIssuanceDate(String contactIdIssuanceDate) {
        this.contactIdIssuanceDate = contactIdIssuanceDate == null ? null : contactIdIssuanceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_id_expiration_date
     *
     * @return the value of ml_borrower.contact_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactIdExpirationDate() {
        return contactIdExpirationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_id_expiration_date
     *
     * @param contactIdExpirationDate the value for ml_borrower.contact_id_expiration_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactIdExpirationDate(String contactIdExpirationDate) {
        this.contactIdExpirationDate = contactIdExpirationDate == null ? null : contactIdExpirationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_job_type
     *
     * @return the value of ml_borrower.contact_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactJobType() {
        return contactJobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_job_type
     *
     * @param contactJobType the value for ml_borrower.contact_job_type
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactJobType(String contactJobType) {
        this.contactJobType = contactJobType == null ? null : contactJobType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_job_company
     *
     * @return the value of ml_borrower.contact_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactJobCompany() {
        return contactJobCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_job_company
     *
     * @param contactJobCompany the value for ml_borrower.contact_job_company
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactJobCompany(String contactJobCompany) {
        this.contactJobCompany = contactJobCompany == null ? null : contactJobCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_job_dept
     *
     * @return the value of ml_borrower.contact_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactJobDept() {
        return contactJobDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_job_dept
     *
     * @param contactJobDept the value for ml_borrower.contact_job_dept
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactJobDept(String contactJobDept) {
        this.contactJobDept = contactJobDept == null ? null : contactJobDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_job_duty
     *
     * @return the value of ml_borrower.contact_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactJobDuty() {
        return contactJobDuty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_job_duty
     *
     * @param contactJobDuty the value for ml_borrower.contact_job_duty
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactJobDuty(String contactJobDuty) {
        this.contactJobDuty = contactJobDuty == null ? null : contactJobDuty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_job_begin_date
     *
     * @return the value of ml_borrower.contact_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactJobBeginDate() {
        return contactJobBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_job_begin_date
     *
     * @param contactJobBeginDate the value for ml_borrower.contact_job_begin_date
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactJobBeginDate(String contactJobBeginDate) {
        this.contactJobBeginDate = contactJobBeginDate == null ? null : contactJobBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_company_addr
     *
     * @return the value of ml_borrower.contact_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactCompanyAddr() {
        return contactCompanyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_company_addr
     *
     * @param contactCompanyAddr the value for ml_borrower.contact_company_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactCompanyAddr(String contactCompanyAddr) {
        this.contactCompanyAddr = contactCompanyAddr == null ? null : contactCompanyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_company_post
     *
     * @return the value of ml_borrower.contact_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactCompanyPost() {
        return contactCompanyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_company_post
     *
     * @param contactCompanyPost the value for ml_borrower.contact_company_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactCompanyPost(String contactCompanyPost) {
        this.contactCompanyPost = contactCompanyPost == null ? null : contactCompanyPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_home_addr
     *
     * @return the value of ml_borrower.contact_home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactHomeAddr() {
        return contactHomeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_home_addr
     *
     * @param contactHomeAddr the value for ml_borrower.contact_home_addr
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactHomeAddr(String contactHomeAddr) {
        this.contactHomeAddr = contactHomeAddr == null ? null : contactHomeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_home_post
     *
     * @return the value of ml_borrower.contact_home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactHomePost() {
        return contactHomePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_home_post
     *
     * @param contactHomePost the value for ml_borrower.contact_home_post
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactHomePost(String contactHomePost) {
        this.contactHomePost = contactHomePost == null ? null : contactHomePost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_mobile_phone1
     *
     * @return the value of ml_borrower.contact_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactMobilePhone1() {
        return contactMobilePhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_mobile_phone1
     *
     * @param contactMobilePhone1 the value for ml_borrower.contact_mobile_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactMobilePhone1(String contactMobilePhone1) {
        this.contactMobilePhone1 = contactMobilePhone1 == null ? null : contactMobilePhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_mobile_phone2
     *
     * @return the value of ml_borrower.contact_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactMobilePhone2() {
        return contactMobilePhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_mobile_phone2
     *
     * @param contactMobilePhone2 the value for ml_borrower.contact_mobile_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactMobilePhone2(String contactMobilePhone2) {
        this.contactMobilePhone2 = contactMobilePhone2 == null ? null : contactMobilePhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_fixed_phone1
     *
     * @return the value of ml_borrower.contact_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactFixedPhone1() {
        return contactFixedPhone1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_fixed_phone1
     *
     * @param contactFixedPhone1 the value for ml_borrower.contact_fixed_phone1
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactFixedPhone1(String contactFixedPhone1) {
        this.contactFixedPhone1 = contactFixedPhone1 == null ? null : contactFixedPhone1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_fixed_phone2
     *
     * @return the value of ml_borrower.contact_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactFixedPhone2() {
        return contactFixedPhone2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_fixed_phone2
     *
     * @param contactFixedPhone2 the value for ml_borrower.contact_fixed_phone2
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactFixedPhone2(String contactFixedPhone2) {
        this.contactFixedPhone2 = contactFixedPhone2 == null ? null : contactFixedPhone2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_email
     *
     * @return the value of ml_borrower.contact_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_email
     *
     * @param contactEmail the value for ml_borrower.contact_email
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail == null ? null : contactEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_qq
     *
     * @return the value of ml_borrower.contact_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactQq() {
        return contactQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_qq
     *
     * @param contactQq the value for ml_borrower.contact_qq
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactQq(String contactQq) {
        this.contactQq = contactQq == null ? null : contactQq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.contact_wechat
     *
     * @return the value of ml_borrower.contact_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getContactWechat() {
        return contactWechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.contact_wechat
     *
     * @param contactWechat the value for ml_borrower.contact_wechat
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setContactWechat(String contactWechat) {
        this.contactWechat = contactWechat == null ? null : contactWechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.cretid_limit
     *
     * @return the value of ml_borrower.cretid_limit
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public BigDecimal getCretidLimit() {
        return cretidLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.cretid_limit
     *
     * @param cretidLimit the value for ml_borrower.cretid_limit
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCretidLimit(BigDecimal cretidLimit) {
        this.cretidLimit = cretidLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.credit_deadline
     *
     * @return the value of ml_borrower.credit_deadline
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getCreditDeadline() {
        return creditDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.credit_deadline
     *
     * @param creditDeadline the value for ml_borrower.credit_deadline
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCreditDeadline(String creditDeadline) {
        this.creditDeadline = creditDeadline == null ? null : creditDeadline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.is_pass_due
     *
     * @return the value of ml_borrower.is_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getIsPassDue() {
        return isPassDue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.is_pass_due
     *
     * @param isPassDue the value for ml_borrower.is_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setIsPassDue(String isPassDue) {
        this.isPassDue = isPassDue == null ? null : isPassDue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.longest_pass_due
     *
     * @return the value of ml_borrower.longest_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getLongestPassDue() {
        return longestPassDue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.longest_pass_due
     *
     * @param longestPassDue the value for ml_borrower.longest_pass_due
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setLongestPassDue(String longestPassDue) {
        this.longestPassDue = longestPassDue == null ? null : longestPassDue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.bank
     *
     * @return the value of ml_borrower.bank
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.bank
     *
     * @param bank the value for ml_borrower.bank
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.account_outlet
     *
     * @return the value of ml_borrower.account_outlet
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getAccountOutlet() {
        return accountOutlet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.account_outlet
     *
     * @param accountOutlet the value for ml_borrower.account_outlet
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setAccountOutlet(String accountOutlet) {
        this.accountOutlet = accountOutlet == null ? null : accountOutlet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.account
     *
     * @return the value of ml_borrower.account
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.account
     *
     * @param account the value for ml_borrower.account
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.enter_user_id
     *
     * @return the value of ml_borrower.enter_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public Long getEnterUserId() {
        return enterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.enter_user_id
     *
     * @param enterUserId the value for ml_borrower.enter_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setEnterUserId(Long enterUserId) {
        this.enterUserId = enterUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.check_user_id
     *
     * @return the value of ml_borrower.check_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public Long getCheckUserId() {
        return checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.check_user_id
     *
     * @param checkUserId the value for ml_borrower.check_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setCheckUserId(Long checkUserId) {
        this.checkUserId = checkUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.last_update_time
     *
     * @return the value of ml_borrower.last_update_time
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.last_update_time
     *
     * @param lastUpdateTime the value for ml_borrower.last_update_time
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.last_update_user_id
     *
     * @return the value of ml_borrower.last_update_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public Long getLastUpdateUserId() {
        return lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.last_update_user_id
     *
     * @param lastUpdateUserId the value for ml_borrower.last_update_user_id
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setLastUpdateUserId(Long lastUpdateUserId) {
        this.lastUpdateUserId = lastUpdateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_borrower.marketing_staff
     *
     * @return the value of ml_borrower.marketing_staff
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public String getMarketingStaff() {
        return marketingStaff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_borrower.marketing_staff
     *
     * @param marketingStaff the value for ml_borrower.marketing_staff
     *
     * @mbggenerated Sun Jun 29 16:37:05 CST 2014
     */
    public void setMarketingStaff(String marketingStaff) {
        this.marketingStaff = marketingStaff == null ? null : marketingStaff.trim();
    }
}