package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MlCorpCustInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public MlCorpCustInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCustNoIsNull() {
			addCriterion("CUST_NO is null");
			return (Criteria) this;
		}

		public Criteria andCustNoIsNotNull() {
			addCriterion("CUST_NO is not null");
			return (Criteria) this;
		}

		public Criteria andCustNoEqualTo(String value) {
			addCriterion("CUST_NO =", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoNotEqualTo(String value) {
			addCriterion("CUST_NO <>", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoGreaterThan(String value) {
			addCriterion("CUST_NO >", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoGreaterThanOrEqualTo(String value) {
			addCriterion("CUST_NO >=", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoLessThan(String value) {
			addCriterion("CUST_NO <", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoLessThanOrEqualTo(String value) {
			addCriterion("CUST_NO <=", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoLike(String value) {
			addCriterion("CUST_NO like", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoNotLike(String value) {
			addCriterion("CUST_NO not like", value, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoIn(List<String> values) {
			addCriterion("CUST_NO in", values, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoNotIn(List<String> values) {
			addCriterion("CUST_NO not in", values, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoBetween(String value1, String value2) {
			addCriterion("CUST_NO between", value1, value2, "custNo");
			return (Criteria) this;
		}

		public Criteria andCustNoNotBetween(String value1, String value2) {
			addCriterion("CUST_NO not between", value1, value2, "custNo");
			return (Criteria) this;
		}

		public Criteria andCompNameIsNull() {
			addCriterion("COMP_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCompNameIsNotNull() {
			addCriterion("COMP_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCompNameEqualTo(String value) {
			addCriterion("COMP_NAME =", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameNotEqualTo(String value) {
			addCriterion("COMP_NAME <>", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameGreaterThan(String value) {
			addCriterion("COMP_NAME >", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameGreaterThanOrEqualTo(String value) {
			addCriterion("COMP_NAME >=", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameLessThan(String value) {
			addCriterion("COMP_NAME <", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameLessThanOrEqualTo(String value) {
			addCriterion("COMP_NAME <=", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameLike(String value) {
			addCriterion("COMP_NAME like", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameNotLike(String value) {
			addCriterion("COMP_NAME not like", value, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameIn(List<String> values) {
			addCriterion("COMP_NAME in", values, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameNotIn(List<String> values) {
			addCriterion("COMP_NAME not in", values, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameBetween(String value1, String value2) {
			addCriterion("COMP_NAME between", value1, value2, "compName");
			return (Criteria) this;
		}

		public Criteria andCompNameNotBetween(String value1, String value2) {
			addCriterion("COMP_NAME not between", value1, value2, "compName");
			return (Criteria) this;
		}

		public Criteria andRegAddrIsNull() {
			addCriterion("REG_ADDR is null");
			return (Criteria) this;
		}

		public Criteria andRegAddrIsNotNull() {
			addCriterion("REG_ADDR is not null");
			return (Criteria) this;
		}

		public Criteria andRegAddrEqualTo(String value) {
			addCriterion("REG_ADDR =", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrNotEqualTo(String value) {
			addCriterion("REG_ADDR <>", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrGreaterThan(String value) {
			addCriterion("REG_ADDR >", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrGreaterThanOrEqualTo(String value) {
			addCriterion("REG_ADDR >=", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrLessThan(String value) {
			addCriterion("REG_ADDR <", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrLessThanOrEqualTo(String value) {
			addCriterion("REG_ADDR <=", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrLike(String value) {
			addCriterion("REG_ADDR like", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrNotLike(String value) {
			addCriterion("REG_ADDR not like", value, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrIn(List<String> values) {
			addCriterion("REG_ADDR in", values, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrNotIn(List<String> values) {
			addCriterion("REG_ADDR not in", values, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrBetween(String value1, String value2) {
			addCriterion("REG_ADDR between", value1, value2, "regAddr");
			return (Criteria) this;
		}

		public Criteria andRegAddrNotBetween(String value1, String value2) {
			addCriterion("REG_ADDR not between", value1, value2, "regAddr");
			return (Criteria) this;
		}

		public Criteria andCompTypeIsNull() {
			addCriterion("COMP_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andCompTypeIsNotNull() {
			addCriterion("COMP_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andCompTypeEqualTo(String value) {
			addCriterion("COMP_TYPE =", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeNotEqualTo(String value) {
			addCriterion("COMP_TYPE <>", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeGreaterThan(String value) {
			addCriterion("COMP_TYPE >", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeGreaterThanOrEqualTo(String value) {
			addCriterion("COMP_TYPE >=", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeLessThan(String value) {
			addCriterion("COMP_TYPE <", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeLessThanOrEqualTo(String value) {
			addCriterion("COMP_TYPE <=", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeLike(String value) {
			addCriterion("COMP_TYPE like", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeNotLike(String value) {
			addCriterion("COMP_TYPE not like", value, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeIn(List<String> values) {
			addCriterion("COMP_TYPE in", values, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeNotIn(List<String> values) {
			addCriterion("COMP_TYPE not in", values, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeBetween(String value1, String value2) {
			addCriterion("COMP_TYPE between", value1, value2, "compType");
			return (Criteria) this;
		}

		public Criteria andCompTypeNotBetween(String value1, String value2) {
			addCriterion("COMP_TYPE not between", value1, value2, "compType");
			return (Criteria) this;
		}

		public Criteria andEstablishDateIsNull() {
			addCriterion("ESTABLISH_DATE is null");
			return (Criteria) this;
		}

		public Criteria andEstablishDateIsNotNull() {
			addCriterion("ESTABLISH_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andEstablishDateEqualTo(Date value) {
			addCriterion("ESTABLISH_DATE =", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateNotEqualTo(Date value) {
			addCriterion("ESTABLISH_DATE <>", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateGreaterThan(Date value) {
			addCriterion("ESTABLISH_DATE >", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateGreaterThanOrEqualTo(Date value) {
			addCriterion("ESTABLISH_DATE >=", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateLessThan(Date value) {
			addCriterion("ESTABLISH_DATE <", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateLessThanOrEqualTo(Date value) {
			addCriterion("ESTABLISH_DATE <=", value, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateIn(List<Date> values) {
			addCriterion("ESTABLISH_DATE in", values, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateNotIn(List<Date> values) {
			addCriterion("ESTABLISH_DATE not in", values, "establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateBetween(Date value1, Date value2) {
			addCriterion("ESTABLISH_DATE between", value1, value2,
					"establishDate");
			return (Criteria) this;
		}

		public Criteria andEstablishDateNotBetween(Date value1, Date value2) {
			addCriterion("ESTABLISH_DATE not between", value1, value2,
					"establishDate");
			return (Criteria) this;
		}

		public Criteria andLegalPersonIsNull() {
			addCriterion("LEGAL_PERSON is null");
			return (Criteria) this;
		}

		public Criteria andLegalPersonIsNotNull() {
			addCriterion("LEGAL_PERSON is not null");
			return (Criteria) this;
		}

		public Criteria andLegalPersonEqualTo(String value) {
			addCriterion("LEGAL_PERSON =", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonNotEqualTo(String value) {
			addCriterion("LEGAL_PERSON <>", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonGreaterThan(String value) {
			addCriterion("LEGAL_PERSON >", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonGreaterThanOrEqualTo(String value) {
			addCriterion("LEGAL_PERSON >=", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonLessThan(String value) {
			addCriterion("LEGAL_PERSON <", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonLessThanOrEqualTo(String value) {
			addCriterion("LEGAL_PERSON <=", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonLike(String value) {
			addCriterion("LEGAL_PERSON like", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonNotLike(String value) {
			addCriterion("LEGAL_PERSON not like", value, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonIn(List<String> values) {
			addCriterion("LEGAL_PERSON in", values, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonNotIn(List<String> values) {
			addCriterion("LEGAL_PERSON not in", values, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonBetween(String value1, String value2) {
			addCriterion("LEGAL_PERSON between", value1, value2, "legalPerson");
			return (Criteria) this;
		}

		public Criteria andLegalPersonNotBetween(String value1, String value2) {
			addCriterion("LEGAL_PERSON not between", value1, value2,
					"legalPerson");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeIsNull() {
			addCriterion("LP_ID_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeIsNotNull() {
			addCriterion("LP_ID_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeEqualTo(String value) {
			addCriterion("LP_ID_TYPE =", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeNotEqualTo(String value) {
			addCriterion("LP_ID_TYPE <>", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeGreaterThan(String value) {
			addCriterion("LP_ID_TYPE >", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeGreaterThanOrEqualTo(String value) {
			addCriterion("LP_ID_TYPE >=", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeLessThan(String value) {
			addCriterion("LP_ID_TYPE <", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeLessThanOrEqualTo(String value) {
			addCriterion("LP_ID_TYPE <=", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeLike(String value) {
			addCriterion("LP_ID_TYPE like", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeNotLike(String value) {
			addCriterion("LP_ID_TYPE not like", value, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeIn(List<String> values) {
			addCriterion("LP_ID_TYPE in", values, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeNotIn(List<String> values) {
			addCriterion("LP_ID_TYPE not in", values, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeBetween(String value1, String value2) {
			addCriterion("LP_ID_TYPE between", value1, value2, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdTypeNotBetween(String value1, String value2) {
			addCriterion("LP_ID_TYPE not between", value1, value2, "lpIdType");
			return (Criteria) this;
		}

		public Criteria andLpIdNoIsNull() {
			addCriterion("LP_ID_NO is null");
			return (Criteria) this;
		}

		public Criteria andLpIdNoIsNotNull() {
			addCriterion("LP_ID_NO is not null");
			return (Criteria) this;
		}

		public Criteria andLpIdNoEqualTo(String value) {
			addCriterion("LP_ID_NO =", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoNotEqualTo(String value) {
			addCriterion("LP_ID_NO <>", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoGreaterThan(String value) {
			addCriterion("LP_ID_NO >", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoGreaterThanOrEqualTo(String value) {
			addCriterion("LP_ID_NO >=", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoLessThan(String value) {
			addCriterion("LP_ID_NO <", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoLessThanOrEqualTo(String value) {
			addCriterion("LP_ID_NO <=", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoLike(String value) {
			addCriterion("LP_ID_NO like", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoNotLike(String value) {
			addCriterion("LP_ID_NO not like", value, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoIn(List<String> values) {
			addCriterion("LP_ID_NO in", values, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoNotIn(List<String> values) {
			addCriterion("LP_ID_NO not in", values, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoBetween(String value1, String value2) {
			addCriterion("LP_ID_NO between", value1, value2, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpIdNoNotBetween(String value1, String value2) {
			addCriterion("LP_ID_NO not between", value1, value2, "lpIdNo");
			return (Criteria) this;
		}

		public Criteria andLpNativeIsNull() {
			addCriterion("LP_NATIVE is null");
			return (Criteria) this;
		}

		public Criteria andLpNativeIsNotNull() {
			addCriterion("LP_NATIVE is not null");
			return (Criteria) this;
		}

		public Criteria andLpNativeEqualTo(String value) {
			addCriterion("LP_NATIVE =", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeNotEqualTo(String value) {
			addCriterion("LP_NATIVE <>", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeGreaterThan(String value) {
			addCriterion("LP_NATIVE >", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeGreaterThanOrEqualTo(String value) {
			addCriterion("LP_NATIVE >=", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeLessThan(String value) {
			addCriterion("LP_NATIVE <", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeLessThanOrEqualTo(String value) {
			addCriterion("LP_NATIVE <=", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeLike(String value) {
			addCriterion("LP_NATIVE like", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeNotLike(String value) {
			addCriterion("LP_NATIVE not like", value, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeIn(List<String> values) {
			addCriterion("LP_NATIVE in", values, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeNotIn(List<String> values) {
			addCriterion("LP_NATIVE not in", values, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeBetween(String value1, String value2) {
			addCriterion("LP_NATIVE between", value1, value2, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpNativeNotBetween(String value1, String value2) {
			addCriterion("LP_NATIVE not between", value1, value2, "lpNative");
			return (Criteria) this;
		}

		public Criteria andLpAddrIsNull() {
			addCriterion("LP_ADDR is null");
			return (Criteria) this;
		}

		public Criteria andLpAddrIsNotNull() {
			addCriterion("LP_ADDR is not null");
			return (Criteria) this;
		}

		public Criteria andLpAddrEqualTo(String value) {
			addCriterion("LP_ADDR =", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrNotEqualTo(String value) {
			addCriterion("LP_ADDR <>", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrGreaterThan(String value) {
			addCriterion("LP_ADDR >", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrGreaterThanOrEqualTo(String value) {
			addCriterion("LP_ADDR >=", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrLessThan(String value) {
			addCriterion("LP_ADDR <", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrLessThanOrEqualTo(String value) {
			addCriterion("LP_ADDR <=", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrLike(String value) {
			addCriterion("LP_ADDR like", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrNotLike(String value) {
			addCriterion("LP_ADDR not like", value, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrIn(List<String> values) {
			addCriterion("LP_ADDR in", values, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrNotIn(List<String> values) {
			addCriterion("LP_ADDR not in", values, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrBetween(String value1, String value2) {
			addCriterion("LP_ADDR between", value1, value2, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andLpAddrNotBetween(String value1, String value2) {
			addCriterion("LP_ADDR not between", value1, value2, "lpAddr");
			return (Criteria) this;
		}

		public Criteria andBusiScopeIsNull() {
			addCriterion("BUSI_SCOPE is null");
			return (Criteria) this;
		}

		public Criteria andBusiScopeIsNotNull() {
			addCriterion("BUSI_SCOPE is not null");
			return (Criteria) this;
		}

		public Criteria andBusiScopeEqualTo(String value) {
			addCriterion("BUSI_SCOPE =", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeNotEqualTo(String value) {
			addCriterion("BUSI_SCOPE <>", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeGreaterThan(String value) {
			addCriterion("BUSI_SCOPE >", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeGreaterThanOrEqualTo(String value) {
			addCriterion("BUSI_SCOPE >=", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeLessThan(String value) {
			addCriterion("BUSI_SCOPE <", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeLessThanOrEqualTo(String value) {
			addCriterion("BUSI_SCOPE <=", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeLike(String value) {
			addCriterion("BUSI_SCOPE like", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeNotLike(String value) {
			addCriterion("BUSI_SCOPE not like", value, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeIn(List<String> values) {
			addCriterion("BUSI_SCOPE in", values, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeNotIn(List<String> values) {
			addCriterion("BUSI_SCOPE not in", values, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeBetween(String value1, String value2) {
			addCriterion("BUSI_SCOPE between", value1, value2, "busiScope");
			return (Criteria) this;
		}

		public Criteria andBusiScopeNotBetween(String value1, String value2) {
			addCriterion("BUSI_SCOPE not between", value1, value2, "busiScope");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsIsNull() {
			addCriterion("LAST_YEAR_ASSETS is null");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsIsNotNull() {
			addCriterion("LAST_YEAR_ASSETS is not null");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS =", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsNotEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS <>", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsGreaterThan(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS >", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS >=", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsLessThan(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS <", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_ASSETS <=", value, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_ASSETS in", values, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsNotIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_ASSETS not in", values, "lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_ASSETS between", value1, value2,
					"lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearAssetsNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_ASSETS not between", value1, value2,
					"lastYearAssets");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesIsNull() {
			addCriterion("LAST_YEAR_LIABILITIES is null");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesIsNotNull() {
			addCriterion("LAST_YEAR_LIABILITIES is not null");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES =", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesNotEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES <>", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesGreaterThan(BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES >", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES >=", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesLessThan(BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES <", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_LIABILITIES <=", value,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_LIABILITIES in", values,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesNotIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_LIABILITIES not in", values,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_LIABILITIES between", value1, value2,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearLiabilitiesNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_LIABILITIES not between", value1, value2,
					"lastYearLiabilities");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountIsNull() {
			addCriterion("LAST_YEAR_SALES_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountIsNotNull() {
			addCriterion("LAST_YEAR_SALES_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT =", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountNotEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT <>", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountGreaterThan(BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT >", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT >=", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountLessThan(BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT <", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_SALES_AMOUNT <=", value,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_SALES_AMOUNT in", values,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountNotIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_SALES_AMOUNT not in", values,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_SALES_AMOUNT between", value1, value2,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearSalesAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_SALES_AMOUNT not between", value1, value2,
					"lastYearSalesAmount");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitIsNull() {
			addCriterion("LAST_YEAR_PROFIT is null");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitIsNotNull() {
			addCriterion("LAST_YEAR_PROFIT is not null");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT =", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitNotEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT <>", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitGreaterThan(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT >", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT >=", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitLessThan(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT <", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PROFIT <=", value, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_PROFIT in", values, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitNotIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_PROFIT not in", values, "lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_PROFIT between", value1, value2,
					"lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearProfitNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_PROFIT not between", value1, value2,
					"lastYearProfit");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxIsNull() {
			addCriterion("LAST_YEAR_PAY_TAX is null");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxIsNotNull() {
			addCriterion("LAST_YEAR_PAY_TAX is not null");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX =", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxNotEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX <>", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxGreaterThan(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX >", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX >=", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxLessThan(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX <", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LAST_YEAR_PAY_TAX <=", value, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_PAY_TAX in", values, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxNotIn(List<BigDecimal> values) {
			addCriterion("LAST_YEAR_PAY_TAX not in", values, "lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_PAY_TAX between", value1, value2,
					"lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andLastYearPayTaxNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LAST_YEAR_PAY_TAX not between", value1, value2,
					"lastYearPayTax");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthIsNull() {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH is null");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthIsNotNull() {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH is not null");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthEqualTo(BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH =", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthNotEqualTo(BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH <>", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthGreaterThan(BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH >", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthGreaterThanOrEqualTo(
				BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH >=", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthLessThan(BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH <", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH <=", value,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthIn(List<BigDecimal> values) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH in", values,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthNotIn(List<BigDecimal> values) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH not in", values,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH between", value1, value2,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andAvgCashFlowInSixmthNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("AVG_CASH_FLOW_IN_SIXMTH not between", value1, value2,
					"avgCashFlowInSixmth");
			return (Criteria) this;
		}

		public Criteria andLoanAmountIsNull() {
			addCriterion("LOAN_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andLoanAmountIsNotNull() {
			addCriterion("LOAN_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andLoanAmountEqualTo(BigDecimal value) {
			addCriterion("LOAN_AMOUNT =", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountNotEqualTo(BigDecimal value) {
			addCriterion("LOAN_AMOUNT <>", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountGreaterThan(BigDecimal value) {
			addCriterion("LOAN_AMOUNT >", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_AMOUNT >=", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountLessThan(BigDecimal value) {
			addCriterion("LOAN_AMOUNT <", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_AMOUNT <=", value, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountIn(List<BigDecimal> values) {
			addCriterion("LOAN_AMOUNT in", values, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountNotIn(List<BigDecimal> values) {
			addCriterion("LOAN_AMOUNT not in", values, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LOAN_AMOUNT between", value1, value2, "loanAmount");
			return (Criteria) this;
		}

		public Criteria andLoanAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LOAN_AMOUNT not between", value1, value2,
					"loanAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountIsNull() {
			addCriterion("REMAIN_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andRemainAmountIsNotNull() {
			addCriterion("REMAIN_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andRemainAmountEqualTo(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT =", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountNotEqualTo(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT <>", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountGreaterThan(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT >", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT >=", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountLessThan(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT <", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("REMAIN_AMOUNT <=", value, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountIn(List<BigDecimal> values) {
			addCriterion("REMAIN_AMOUNT in", values, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountNotIn(List<BigDecimal> values) {
			addCriterion("REMAIN_AMOUNT not in", values, "remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("REMAIN_AMOUNT between", value1, value2,
					"remainAmount");
			return (Criteria) this;
		}

		public Criteria andRemainAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("REMAIN_AMOUNT not between", value1, value2,
					"remainAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountIsNull() {
			addCriterion("PAY_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andPayAmountIsNotNull() {
			addCriterion("PAY_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andPayAmountEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT =", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT <>", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountGreaterThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT >", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT >=", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountLessThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT <", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT <=", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT in", values, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT not in", values, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_AMOUNT between", value1, value2, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("PAY_AMOUNT not between", value1, value2, "payAmount");
			return (Criteria) this;
		}

		public Criteria andLoanRateIsNull() {
			addCriterion("LOAN_RATE is null");
			return (Criteria) this;
		}

		public Criteria andLoanRateIsNotNull() {
			addCriterion("LOAN_RATE is not null");
			return (Criteria) this;
		}

		public Criteria andLoanRateEqualTo(BigDecimal value) {
			addCriterion("LOAN_RATE =", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateNotEqualTo(BigDecimal value) {
			addCriterion("LOAN_RATE <>", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateGreaterThan(BigDecimal value) {
			addCriterion("LOAN_RATE >", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_RATE >=", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateLessThan(BigDecimal value) {
			addCriterion("LOAN_RATE <", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_RATE <=", value, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateIn(List<BigDecimal> values) {
			addCriterion("LOAN_RATE in", values, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateNotIn(List<BigDecimal> values) {
			addCriterion("LOAN_RATE not in", values, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("LOAN_RATE between", value1, value2, "loanRate");
			return (Criteria) this;
		}

		public Criteria andLoanRateNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LOAN_RATE not between", value1, value2, "loanRate");
			return (Criteria) this;
		}

		public Criteria andOverdueFineIsNull() {
			addCriterion("OVERDUE_FINE is null");
			return (Criteria) this;
		}

		public Criteria andOverdueFineIsNotNull() {
			addCriterion("OVERDUE_FINE is not null");
			return (Criteria) this;
		}

		public Criteria andOverdueFineEqualTo(BigDecimal value) {
			addCriterion("OVERDUE_FINE =", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineNotEqualTo(BigDecimal value) {
			addCriterion("OVERDUE_FINE <>", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineGreaterThan(BigDecimal value) {
			addCriterion("OVERDUE_FINE >", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("OVERDUE_FINE >=", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineLessThan(BigDecimal value) {
			addCriterion("OVERDUE_FINE <", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineLessThanOrEqualTo(BigDecimal value) {
			addCriterion("OVERDUE_FINE <=", value, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineIn(List<BigDecimal> values) {
			addCriterion("OVERDUE_FINE in", values, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineNotIn(List<BigDecimal> values) {
			addCriterion("OVERDUE_FINE not in", values, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("OVERDUE_FINE between", value1, value2, "overdueFine");
			return (Criteria) this;
		}

		public Criteria andOverdueFineNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("OVERDUE_FINE not between", value1, value2,
					"overdueFine");
			return (Criteria) this;
		}

		public Criteria andLoanInterestIsNull() {
			addCriterion("LOAN_INTEREST is null");
			return (Criteria) this;
		}

		public Criteria andLoanInterestIsNotNull() {
			addCriterion("LOAN_INTEREST is not null");
			return (Criteria) this;
		}

		public Criteria andLoanInterestEqualTo(BigDecimal value) {
			addCriterion("LOAN_INTEREST =", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestNotEqualTo(BigDecimal value) {
			addCriterion("LOAN_INTEREST <>", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestGreaterThan(BigDecimal value) {
			addCriterion("LOAN_INTEREST >", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_INTEREST >=", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestLessThan(BigDecimal value) {
			addCriterion("LOAN_INTEREST <", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestLessThanOrEqualTo(BigDecimal value) {
			addCriterion("LOAN_INTEREST <=", value, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestIn(List<BigDecimal> values) {
			addCriterion("LOAN_INTEREST in", values, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestNotIn(List<BigDecimal> values) {
			addCriterion("LOAN_INTEREST not in", values, "loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LOAN_INTEREST between", value1, value2,
					"loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanInterestNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("LOAN_INTEREST not between", value1, value2,
					"loanInterest");
			return (Criteria) this;
		}

		public Criteria andLoanCycleIsNull() {
			addCriterion("LOAN_CYCLE is null");
			return (Criteria) this;
		}

		public Criteria andLoanCycleIsNotNull() {
			addCriterion("LOAN_CYCLE is not null");
			return (Criteria) this;
		}

		public Criteria andLoanCycleEqualTo(Integer value) {
			addCriterion("LOAN_CYCLE =", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleNotEqualTo(Integer value) {
			addCriterion("LOAN_CYCLE <>", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleGreaterThan(Integer value) {
			addCriterion("LOAN_CYCLE >", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleGreaterThanOrEqualTo(Integer value) {
			addCriterion("LOAN_CYCLE >=", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleLessThan(Integer value) {
			addCriterion("LOAN_CYCLE <", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleLessThanOrEqualTo(Integer value) {
			addCriterion("LOAN_CYCLE <=", value, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleIn(List<Integer> values) {
			addCriterion("LOAN_CYCLE in", values, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleNotIn(List<Integer> values) {
			addCriterion("LOAN_CYCLE not in", values, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleBetween(Integer value1, Integer value2) {
			addCriterion("LOAN_CYCLE between", value1, value2, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanCycleNotBetween(Integer value1, Integer value2) {
			addCriterion("LOAN_CYCLE not between", value1, value2, "loanCycle");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeIsNull() {
			addCriterion("LOAN_START_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeIsNotNull() {
			addCriterion("LOAN_START_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeEqualTo(Date value) {
			addCriterion("LOAN_START_TIME =", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeNotEqualTo(Date value) {
			addCriterion("LOAN_START_TIME <>", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeGreaterThan(Date value) {
			addCriterion("LOAN_START_TIME >", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("LOAN_START_TIME >=", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeLessThan(Date value) {
			addCriterion("LOAN_START_TIME <", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeLessThanOrEqualTo(Date value) {
			addCriterion("LOAN_START_TIME <=", value, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeIn(List<Date> values) {
			addCriterion("LOAN_START_TIME in", values, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeNotIn(List<Date> values) {
			addCriterion("LOAN_START_TIME not in", values, "loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeBetween(Date value1, Date value2) {
			addCriterion("LOAN_START_TIME between", value1, value2,
					"loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanStartTimeNotBetween(Date value1, Date value2) {
			addCriterion("LOAN_START_TIME not between", value1, value2,
					"loanStartTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeIsNull() {
			addCriterion("LOAN_FINISH_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeIsNotNull() {
			addCriterion("LOAN_FINISH_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeEqualTo(Date value) {
			addCriterion("LOAN_FINISH_TIME =", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeNotEqualTo(Date value) {
			addCriterion("LOAN_FINISH_TIME <>", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeGreaterThan(Date value) {
			addCriterion("LOAN_FINISH_TIME >", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("LOAN_FINISH_TIME >=", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeLessThan(Date value) {
			addCriterion("LOAN_FINISH_TIME <", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeLessThanOrEqualTo(Date value) {
			addCriterion("LOAN_FINISH_TIME <=", value, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeIn(List<Date> values) {
			addCriterion("LOAN_FINISH_TIME in", values, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeNotIn(List<Date> values) {
			addCriterion("LOAN_FINISH_TIME not in", values, "loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeBetween(Date value1, Date value2) {
			addCriterion("LOAN_FINISH_TIME between", value1, value2,
					"loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andLoanFinishTimeNotBetween(Date value1, Date value2) {
			addCriterion("LOAN_FINISH_TIME not between", value1, value2,
					"loanFinishTime");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusIsNull() {
			addCriterion("DELINQ_STATUS is null");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusIsNotNull() {
			addCriterion("DELINQ_STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusEqualTo(String value) {
			addCriterion("DELINQ_STATUS =", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusNotEqualTo(String value) {
			addCriterion("DELINQ_STATUS <>", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusGreaterThan(String value) {
			addCriterion("DELINQ_STATUS >", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusGreaterThanOrEqualTo(String value) {
			addCriterion("DELINQ_STATUS >=", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusLessThan(String value) {
			addCriterion("DELINQ_STATUS <", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusLessThanOrEqualTo(String value) {
			addCriterion("DELINQ_STATUS <=", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusLike(String value) {
			addCriterion("DELINQ_STATUS like", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusNotLike(String value) {
			addCriterion("DELINQ_STATUS not like", value, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusIn(List<String> values) {
			addCriterion("DELINQ_STATUS in", values, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusNotIn(List<String> values) {
			addCriterion("DELINQ_STATUS not in", values, "delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusBetween(String value1, String value2) {
			addCriterion("DELINQ_STATUS between", value1, value2,
					"delinqStatus");
			return (Criteria) this;
		}

		public Criteria andDelinqStatusNotBetween(String value1, String value2) {
			addCriterion("DELINQ_STATUS not between", value1, value2,
					"delinqStatus");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andOperIsNull() {
			addCriterion("OPER is null");
			return (Criteria) this;
		}

		public Criteria andOperIsNotNull() {
			addCriterion("OPER is not null");
			return (Criteria) this;
		}

		public Criteria andOperEqualTo(Long value) {
			addCriterion("OPER =", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotEqualTo(Long value) {
			addCriterion("OPER <>", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperGreaterThan(Long value) {
			addCriterion("OPER >", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperGreaterThanOrEqualTo(Long value) {
			addCriterion("OPER >=", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperLessThan(Long value) {
			addCriterion("OPER <", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperLessThanOrEqualTo(Long value) {
			addCriterion("OPER <=", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperIn(List<Long> values) {
			addCriterion("OPER in", values, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotIn(List<Long> values) {
			addCriterion("OPER not in", values, "oper");
			return (Criteria) this;
		}

		public Criteria andOperBetween(Long value1, Long value2) {
			addCriterion("OPER between", value1, value2, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotBetween(Long value1, Long value2) {
			addCriterion("OPER not between", value1, value2, "oper");
			return (Criteria) this;
		}

		public Criteria andOperTimeIsNull() {
			addCriterion("OPER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andOperTimeIsNotNull() {
			addCriterion("OPER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andOperTimeEqualTo(Date value) {
			addCriterion("OPER_TIME =", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotEqualTo(Date value) {
			addCriterion("OPER_TIME <>", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeGreaterThan(Date value) {
			addCriterion("OPER_TIME >", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("OPER_TIME >=", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeLessThan(Date value) {
			addCriterion("OPER_TIME <", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeLessThanOrEqualTo(Date value) {
			addCriterion("OPER_TIME <=", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeIn(List<Date> values) {
			addCriterion("OPER_TIME in", values, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotIn(List<Date> values) {
			addCriterion("OPER_TIME not in", values, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeBetween(Date value1, Date value2) {
			addCriterion("OPER_TIME between", value1, value2, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotBetween(Date value1, Date value2) {
			addCriterion("OPER_TIME not between", value1, value2, "operTime");
			return (Criteria) this;
		}

		public Criteria andOfferLoanIsNull() {
			addCriterion("OFFER_LOAN is null");
			return (Criteria) this;
		}

		public Criteria andOfferLoanIsNotNull() {
			addCriterion("OFFER_LOAN is not null");
			return (Criteria) this;
		}

		public Criteria andOfferLoanEqualTo(BigDecimal value) {
			addCriterion("OFFER_LOAN =", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanNotEqualTo(BigDecimal value) {
			addCriterion("OFFER_LOAN <>", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanGreaterThan(BigDecimal value) {
			addCriterion("OFFER_LOAN >", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("OFFER_LOAN >=", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanLessThan(BigDecimal value) {
			addCriterion("OFFER_LOAN <", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanLessThanOrEqualTo(BigDecimal value) {
			addCriterion("OFFER_LOAN <=", value, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanIn(List<BigDecimal> values) {
			addCriterion("OFFER_LOAN in", values, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanNotIn(List<BigDecimal> values) {
			addCriterion("OFFER_LOAN not in", values, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("OFFER_LOAN between", value1, value2, "offerLoan");
			return (Criteria) this;
		}

		public Criteria andOfferLoanNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("OFFER_LOAN not between", value1, value2, "offerLoan");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ml_corp_cust_info
	 * @mbggenerated  Thu Oct 30 21:06:25 GMT+08:00 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ml_corp_cust_info
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}