package com.wealth.miniloan.entity;

import java.util.Date;

public class MlInteCheckItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.ITEM_ID
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.ITEM_NAME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.ITEM_DESC
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.ITEM_TYPE
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.STATUS
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.CREATOR
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ml_inte_check_item.CREATE_TIME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.ITEM_ID
     *
     * @return the value of ml_inte_check_item.ITEM_ID
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.ITEM_ID
     *
     * @param itemId the value for ml_inte_check_item.ITEM_ID
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.ITEM_NAME
     *
     * @return the value of ml_inte_check_item.ITEM_NAME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.ITEM_NAME
     *
     * @param itemName the value for ml_inte_check_item.ITEM_NAME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.ITEM_DESC
     *
     * @return the value of ml_inte_check_item.ITEM_DESC
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.ITEM_DESC
     *
     * @param itemDesc the value for ml_inte_check_item.ITEM_DESC
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc == null ? null : itemDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.ITEM_TYPE
     *
     * @return the value of ml_inte_check_item.ITEM_TYPE
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.ITEM_TYPE
     *
     * @param itemType the value for ml_inte_check_item.ITEM_TYPE
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setItemType(String itemType) {
        this.itemType = itemType == null ? null : itemType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.STATUS
     *
     * @return the value of ml_inte_check_item.STATUS
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.STATUS
     *
     * @param status the value for ml_inte_check_item.STATUS
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.CREATOR
     *
     * @return the value of ml_inte_check_item.CREATOR
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.CREATOR
     *
     * @param creator the value for ml_inte_check_item.CREATOR
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ml_inte_check_item.CREATE_TIME
     *
     * @return the value of ml_inte_check_item.CREATE_TIME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ml_inte_check_item.CREATE_TIME
     *
     * @param createTime the value for ml_inte_check_item.CREATE_TIME
     *
     * @mbggenerated Mon Oct 20 16:00:16 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}