package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MlLoanReceipt {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.RECEIPT_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private Long receiptId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.LOAN_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private Long loanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_AMOUNT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private BigDecimal offerAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_AMOUNT_SUM
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private BigDecimal offerAmountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_AMOUNT_REMAIN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private BigDecimal offerAmountRemain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_ACCT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private String offerAcct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_MAN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private String offerMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OFFER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private Date offerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.RECEIPT_NO
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private String receiptNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.RECEIPT_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private String receiptName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.RECEIPT_PHYSICAL_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private String receiptPhysicalName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OPER
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private Long oper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_loan_receipt.OPER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	private Date operTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.RECEIPT_ID
	 * @return  the value of ml_loan_receipt.RECEIPT_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public Long getReceiptId() {
		return receiptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.RECEIPT_ID
	 * @param receiptId  the value for ml_loan_receipt.RECEIPT_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setReceiptId(Long receiptId) {
		this.receiptId = receiptId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.LOAN_ID
	 * @return  the value of ml_loan_receipt.LOAN_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public Long getLoanId() {
		return loanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.LOAN_ID
	 * @param loanId  the value for ml_loan_receipt.LOAN_ID
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setLoanId(Long loanId) {
		this.loanId = loanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_AMOUNT
	 * @return  the value of ml_loan_receipt.OFFER_AMOUNT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public BigDecimal getOfferAmount() {
		return offerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_AMOUNT
	 * @param offerAmount  the value for ml_loan_receipt.OFFER_AMOUNT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferAmount(BigDecimal offerAmount) {
		this.offerAmount = offerAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_AMOUNT_SUM
	 * @return  the value of ml_loan_receipt.OFFER_AMOUNT_SUM
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public BigDecimal getOfferAmountSum() {
		return offerAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_AMOUNT_SUM
	 * @param offerAmountSum  the value for ml_loan_receipt.OFFER_AMOUNT_SUM
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferAmountSum(BigDecimal offerAmountSum) {
		this.offerAmountSum = offerAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_AMOUNT_REMAIN
	 * @return  the value of ml_loan_receipt.OFFER_AMOUNT_REMAIN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public BigDecimal getOfferAmountRemain() {
		return offerAmountRemain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_AMOUNT_REMAIN
	 * @param offerAmountRemain  the value for ml_loan_receipt.OFFER_AMOUNT_REMAIN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferAmountRemain(BigDecimal offerAmountRemain) {
		this.offerAmountRemain = offerAmountRemain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_ACCT
	 * @return  the value of ml_loan_receipt.OFFER_ACCT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public String getOfferAcct() {
		return offerAcct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_ACCT
	 * @param offerAcct  the value for ml_loan_receipt.OFFER_ACCT
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferAcct(String offerAcct) {
		this.offerAcct = offerAcct == null ? null : offerAcct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_MAN
	 * @return  the value of ml_loan_receipt.OFFER_MAN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public String getOfferMan() {
		return offerMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_MAN
	 * @param offerMan  the value for ml_loan_receipt.OFFER_MAN
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferMan(String offerMan) {
		this.offerMan = offerMan == null ? null : offerMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OFFER_TIME
	 * @return  the value of ml_loan_receipt.OFFER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public Date getOfferTime() {
		return offerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OFFER_TIME
	 * @param offerTime  the value for ml_loan_receipt.OFFER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOfferTime(Date offerTime) {
		this.offerTime = offerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.RECEIPT_NO
	 * @return  the value of ml_loan_receipt.RECEIPT_NO
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public String getReceiptNo() {
		return receiptNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.RECEIPT_NO
	 * @param receiptNo  the value for ml_loan_receipt.RECEIPT_NO
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setReceiptNo(String receiptNo) {
		this.receiptNo = receiptNo == null ? null : receiptNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.RECEIPT_NAME
	 * @return  the value of ml_loan_receipt.RECEIPT_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public String getReceiptName() {
		return receiptName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.RECEIPT_NAME
	 * @param receiptName  the value for ml_loan_receipt.RECEIPT_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setReceiptName(String receiptName) {
		this.receiptName = receiptName == null ? null : receiptName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.RECEIPT_PHYSICAL_NAME
	 * @return  the value of ml_loan_receipt.RECEIPT_PHYSICAL_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public String getReceiptPhysicalName() {
		return receiptPhysicalName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.RECEIPT_PHYSICAL_NAME
	 * @param receiptPhysicalName  the value for ml_loan_receipt.RECEIPT_PHYSICAL_NAME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setReceiptPhysicalName(String receiptPhysicalName) {
		this.receiptPhysicalName = receiptPhysicalName == null ? null : receiptPhysicalName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OPER
	 * @return  the value of ml_loan_receipt.OPER
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public Long getOper() {
		return oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OPER
	 * @param oper  the value for ml_loan_receipt.OPER
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOper(Long oper) {
		this.oper = oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_loan_receipt.OPER_TIME
	 * @return  the value of ml_loan_receipt.OPER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public Date getOperTime() {
		return operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_loan_receipt.OPER_TIME
	 * @param operTime  the value for ml_loan_receipt.OPER_TIME
	 * @mbggenerated  Sun Nov 02 09:04:10 CST 2014
	 */
	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}
}