package com.wealth.miniloan.entity;

import java.util.Date;

public class MlNameList {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.NAME_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private Long nameId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.NAME_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String nameType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.ID_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String idType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.ID_NO
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String idNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.NAME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.PHONE_NUMBER
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String phoneNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.EMAIL
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.USER_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_name_list.OP_TIME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	private Date opTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.NAME_ID
	 * @return  the value of ml_name_list.NAME_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public Long getNameId() {
		return nameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.NAME_ID
	 * @param nameId  the value for ml_name_list.NAME_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setNameId(Long nameId) {
		this.nameId = nameId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.NAME_TYPE
	 * @return  the value of ml_name_list.NAME_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getNameType() {
		return nameType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.NAME_TYPE
	 * @param nameType  the value for ml_name_list.NAME_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setNameType(String nameType) {
		this.nameType = nameType == null ? null : nameType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.ID_TYPE
	 * @return  the value of ml_name_list.ID_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getIdType() {
		return idType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.ID_TYPE
	 * @param idType  the value for ml_name_list.ID_TYPE
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setIdType(String idType) {
		this.idType = idType == null ? null : idType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.ID_NO
	 * @return  the value of ml_name_list.ID_NO
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getIdNo() {
		return idNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.ID_NO
	 * @param idNo  the value for ml_name_list.ID_NO
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setIdNo(String idNo) {
		this.idNo = idNo == null ? null : idNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.NAME
	 * @return  the value of ml_name_list.NAME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.NAME
	 * @param name  the value for ml_name_list.NAME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.PHONE_NUMBER
	 * @return  the value of ml_name_list.PHONE_NUMBER
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.PHONE_NUMBER
	 * @param phoneNumber  the value for ml_name_list.PHONE_NUMBER
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.EMAIL
	 * @return  the value of ml_name_list.EMAIL
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.EMAIL
	 * @param email  the value for ml_name_list.EMAIL
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.USER_ID
	 * @return  the value of ml_name_list.USER_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.USER_ID
	 * @param userId  the value for ml_name_list.USER_ID
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_name_list.OP_TIME
	 * @return  the value of ml_name_list.OP_TIME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public Date getOpTime() {
		return opTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_name_list.OP_TIME
	 * @param opTime  the value for ml_name_list.OP_TIME
	 * @mbggenerated  Sat Oct 25 13:37:59 CST 2014
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}
}