package com.wealth.miniloan.entity;

import java.math.BigDecimal;

public class MlNaturalCredit {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.APP_NO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private String appNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.HAS_CREDIT_INFO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private String hasCreditInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer ccCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.NEW_CC_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer newCcIn3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LAST_ACTIVE_CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer lastActiveCcCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.MAX_PAST_DUE_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer maxPastDueIn24mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.NOT_MINI_PAY_COUNT_IN12MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer notMiniPayCountIn12mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.MAX_M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer maxMIn3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CURR_PAST_DUE_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer currPastDueCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_MAX_DELIQ_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer loanMaxDeliqIn24mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_CURR_DELIQ
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer loanCurrDeliq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_CURR_AMOUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private BigDecimal loanCurrAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CC_M0_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer ccM0In3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CC_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer ccM1In3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CC_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer ccM2mIn3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_MO_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer loanMoIn3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer loanM1In3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.LOAN_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer loanM2mIn3mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.CTRANS_OR_LOAN_IN6MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer ctransOrLoanIn6mth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.PAST_DUE_TIMES
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer pastDueTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private Integer highestDelinquencyCycle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_natural_credit_info.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	private BigDecimal amountOfDelinquency;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.APP_NO
	 * @return  the value of ml_natural_credit_info.APP_NO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public String getAppNo() {
		return appNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.APP_NO
	 * @param appNo  the value for ml_natural_credit_info.APP_NO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setAppNo(String appNo) {
		this.appNo = appNo == null ? null : appNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.HAS_CREDIT_INFO
	 * @return  the value of ml_natural_credit_info.HAS_CREDIT_INFO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public String getHasCreditInfo() {
		return hasCreditInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.HAS_CREDIT_INFO
	 * @param hasCreditInfo  the value for ml_natural_credit_info.HAS_CREDIT_INFO
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setHasCreditInfo(String hasCreditInfo) {
		this.hasCreditInfo = hasCreditInfo == null ? null : hasCreditInfo
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CC_COUNT
	 * @return  the value of ml_natural_credit_info.CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCcCount() {
		return ccCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CC_COUNT
	 * @param ccCount  the value for ml_natural_credit_info.CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCcCount(Integer ccCount) {
		this.ccCount = ccCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.NEW_CC_IN3MTH
	 * @return  the value of ml_natural_credit_info.NEW_CC_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getNewCcIn3mth() {
		return newCcIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.NEW_CC_IN3MTH
	 * @param newCcIn3mth  the value for ml_natural_credit_info.NEW_CC_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setNewCcIn3mth(Integer newCcIn3mth) {
		this.newCcIn3mth = newCcIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LAST_ACTIVE_CC_COUNT
	 * @return  the value of ml_natural_credit_info.LAST_ACTIVE_CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLastActiveCcCount() {
		return lastActiveCcCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LAST_ACTIVE_CC_COUNT
	 * @param lastActiveCcCount  the value for ml_natural_credit_info.LAST_ACTIVE_CC_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLastActiveCcCount(Integer lastActiveCcCount) {
		this.lastActiveCcCount = lastActiveCcCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.MAX_PAST_DUE_IN24MTH
	 * @return  the value of ml_natural_credit_info.MAX_PAST_DUE_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getMaxPastDueIn24mth() {
		return maxPastDueIn24mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.MAX_PAST_DUE_IN24MTH
	 * @param maxPastDueIn24mth  the value for ml_natural_credit_info.MAX_PAST_DUE_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setMaxPastDueIn24mth(Integer maxPastDueIn24mth) {
		this.maxPastDueIn24mth = maxPastDueIn24mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.NOT_MINI_PAY_COUNT_IN12MTH
	 * @return  the value of ml_natural_credit_info.NOT_MINI_PAY_COUNT_IN12MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getNotMiniPayCountIn12mth() {
		return notMiniPayCountIn12mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.NOT_MINI_PAY_COUNT_IN12MTH
	 * @param notMiniPayCountIn12mth  the value for ml_natural_credit_info.NOT_MINI_PAY_COUNT_IN12MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setNotMiniPayCountIn12mth(Integer notMiniPayCountIn12mth) {
		this.notMiniPayCountIn12mth = notMiniPayCountIn12mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.MAX_M_IN3MTH
	 * @return  the value of ml_natural_credit_info.MAX_M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getMaxMIn3mth() {
		return maxMIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.MAX_M_IN3MTH
	 * @param maxMIn3mth  the value for ml_natural_credit_info.MAX_M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setMaxMIn3mth(Integer maxMIn3mth) {
		this.maxMIn3mth = maxMIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CURR_PAST_DUE_COUNT
	 * @return  the value of ml_natural_credit_info.CURR_PAST_DUE_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCurrPastDueCount() {
		return currPastDueCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CURR_PAST_DUE_COUNT
	 * @param currPastDueCount  the value for ml_natural_credit_info.CURR_PAST_DUE_COUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCurrPastDueCount(Integer currPastDueCount) {
		this.currPastDueCount = currPastDueCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_MAX_DELIQ_IN24MTH
	 * @return  the value of ml_natural_credit_info.LOAN_MAX_DELIQ_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLoanMaxDeliqIn24mth() {
		return loanMaxDeliqIn24mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_MAX_DELIQ_IN24MTH
	 * @param loanMaxDeliqIn24mth  the value for ml_natural_credit_info.LOAN_MAX_DELIQ_IN24MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanMaxDeliqIn24mth(Integer loanMaxDeliqIn24mth) {
		this.loanMaxDeliqIn24mth = loanMaxDeliqIn24mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_CURR_DELIQ
	 * @return  the value of ml_natural_credit_info.LOAN_CURR_DELIQ
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLoanCurrDeliq() {
		return loanCurrDeliq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_CURR_DELIQ
	 * @param loanCurrDeliq  the value for ml_natural_credit_info.LOAN_CURR_DELIQ
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanCurrDeliq(Integer loanCurrDeliq) {
		this.loanCurrDeliq = loanCurrDeliq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_CURR_AMOUNT
	 * @return  the value of ml_natural_credit_info.LOAN_CURR_AMOUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public BigDecimal getLoanCurrAmount() {
		return loanCurrAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_CURR_AMOUNT
	 * @param loanCurrAmount  the value for ml_natural_credit_info.LOAN_CURR_AMOUNT
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanCurrAmount(BigDecimal loanCurrAmount) {
		this.loanCurrAmount = loanCurrAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CC_M0_IN3MTH
	 * @return  the value of ml_natural_credit_info.CC_M0_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCcM0In3mth() {
		return ccM0In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CC_M0_IN3MTH
	 * @param ccM0In3mth  the value for ml_natural_credit_info.CC_M0_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCcM0In3mth(Integer ccM0In3mth) {
		this.ccM0In3mth = ccM0In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CC_M1_IN3MTH
	 * @return  the value of ml_natural_credit_info.CC_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCcM1In3mth() {
		return ccM1In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CC_M1_IN3MTH
	 * @param ccM1In3mth  the value for ml_natural_credit_info.CC_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCcM1In3mth(Integer ccM1In3mth) {
		this.ccM1In3mth = ccM1In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CC_M2M_IN3MTH
	 * @return  the value of ml_natural_credit_info.CC_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCcM2mIn3mth() {
		return ccM2mIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CC_M2M_IN3MTH
	 * @param ccM2mIn3mth  the value for ml_natural_credit_info.CC_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCcM2mIn3mth(Integer ccM2mIn3mth) {
		this.ccM2mIn3mth = ccM2mIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_MO_IN3MTH
	 * @return  the value of ml_natural_credit_info.LOAN_MO_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLoanMoIn3mth() {
		return loanMoIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_MO_IN3MTH
	 * @param loanMoIn3mth  the value for ml_natural_credit_info.LOAN_MO_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanMoIn3mth(Integer loanMoIn3mth) {
		this.loanMoIn3mth = loanMoIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_M1_IN3MTH
	 * @return  the value of ml_natural_credit_info.LOAN_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLoanM1In3mth() {
		return loanM1In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_M1_IN3MTH
	 * @param loanM1In3mth  the value for ml_natural_credit_info.LOAN_M1_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanM1In3mth(Integer loanM1In3mth) {
		this.loanM1In3mth = loanM1In3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.LOAN_M2M_IN3MTH
	 * @return  the value of ml_natural_credit_info.LOAN_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getLoanM2mIn3mth() {
		return loanM2mIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.LOAN_M2M_IN3MTH
	 * @param loanM2mIn3mth  the value for ml_natural_credit_info.LOAN_M2M_IN3MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setLoanM2mIn3mth(Integer loanM2mIn3mth) {
		this.loanM2mIn3mth = loanM2mIn3mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.CTRANS_OR_LOAN_IN6MTH
	 * @return  the value of ml_natural_credit_info.CTRANS_OR_LOAN_IN6MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getCtransOrLoanIn6mth() {
		return ctransOrLoanIn6mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.CTRANS_OR_LOAN_IN6MTH
	 * @param ctransOrLoanIn6mth  the value for ml_natural_credit_info.CTRANS_OR_LOAN_IN6MTH
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setCtransOrLoanIn6mth(Integer ctransOrLoanIn6mth) {
		this.ctransOrLoanIn6mth = ctransOrLoanIn6mth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.PAST_DUE_TIMES
	 * @return  the value of ml_natural_credit_info.PAST_DUE_TIMES
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getPastDueTimes() {
		return pastDueTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.PAST_DUE_TIMES
	 * @param pastDueTimes  the value for ml_natural_credit_info.PAST_DUE_TIMES
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setPastDueTimes(Integer pastDueTimes) {
		this.pastDueTimes = pastDueTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.HIGHEST_DELINQUENCY_CYCLE
	 * @return  the value of ml_natural_credit_info.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public Integer getHighestDelinquencyCycle() {
		return highestDelinquencyCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.HIGHEST_DELINQUENCY_CYCLE
	 * @param highestDelinquencyCycle  the value for ml_natural_credit_info.HIGHEST_DELINQUENCY_CYCLE
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setHighestDelinquencyCycle(Integer highestDelinquencyCycle) {
		this.highestDelinquencyCycle = highestDelinquencyCycle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_natural_credit_info.AMOUNT_OF_DELINQUENCY
	 * @return  the value of ml_natural_credit_info.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public BigDecimal getAmountOfDelinquency() {
		return amountOfDelinquency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_natural_credit_info.AMOUNT_OF_DELINQUENCY
	 * @param amountOfDelinquency  the value for ml_natural_credit_info.AMOUNT_OF_DELINQUENCY
	 * @mbggenerated  Sun Oct 26 13:23:32 GMT+08:00 2014
	 */
	public void setAmountOfDelinquency(BigDecimal amountOfDelinquency) {
		this.amountOfDelinquency = amountOfDelinquency;
	}
}