package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MlPayRecordExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public MlPayRecordExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecordIdIsNull() {
			addCriterion("RECORD_ID is null");
			return (Criteria) this;
		}

		public Criteria andRecordIdIsNotNull() {
			addCriterion("RECORD_ID is not null");
			return (Criteria) this;
		}

		public Criteria andRecordIdEqualTo(Long value) {
			addCriterion("RECORD_ID =", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotEqualTo(Long value) {
			addCriterion("RECORD_ID <>", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThan(Long value) {
			addCriterion("RECORD_ID >", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdGreaterThanOrEqualTo(Long value) {
			addCriterion("RECORD_ID >=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThan(Long value) {
			addCriterion("RECORD_ID <", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdLessThanOrEqualTo(Long value) {
			addCriterion("RECORD_ID <=", value, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdIn(List<Long> values) {
			addCriterion("RECORD_ID in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotIn(List<Long> values) {
			addCriterion("RECORD_ID not in", values, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdBetween(Long value1, Long value2) {
			addCriterion("RECORD_ID between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andRecordIdNotBetween(Long value1, Long value2) {
			addCriterion("RECORD_ID not between", value1, value2, "recordId");
			return (Criteria) this;
		}

		public Criteria andLoanIdIsNull() {
			addCriterion("LOAN_ID is null");
			return (Criteria) this;
		}

		public Criteria andLoanIdIsNotNull() {
			addCriterion("LOAN_ID is not null");
			return (Criteria) this;
		}

		public Criteria andLoanIdEqualTo(Long value) {
			addCriterion("LOAN_ID =", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdNotEqualTo(Long value) {
			addCriterion("LOAN_ID <>", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdGreaterThan(Long value) {
			addCriterion("LOAN_ID >", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdGreaterThanOrEqualTo(Long value) {
			addCriterion("LOAN_ID >=", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdLessThan(Long value) {
			addCriterion("LOAN_ID <", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdLessThanOrEqualTo(Long value) {
			addCriterion("LOAN_ID <=", value, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdIn(List<Long> values) {
			addCriterion("LOAN_ID in", values, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdNotIn(List<Long> values) {
			addCriterion("LOAN_ID not in", values, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdBetween(Long value1, Long value2) {
			addCriterion("LOAN_ID between", value1, value2, "loanId");
			return (Criteria) this;
		}

		public Criteria andLoanIdNotBetween(Long value1, Long value2) {
			addCriterion("LOAN_ID not between", value1, value2, "loanId");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalIsNull() {
			addCriterion("PAY_PRINCIPAL is null");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalIsNotNull() {
			addCriterion("PAY_PRINCIPAL is not null");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalEqualTo(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL =", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalNotEqualTo(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL <>", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalGreaterThan(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL >", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL >=", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalLessThan(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL <", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_PRINCIPAL <=", value, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalIn(List<BigDecimal> values) {
			addCriterion("PAY_PRINCIPAL in", values, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalNotIn(List<BigDecimal> values) {
			addCriterion("PAY_PRINCIPAL not in", values, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_PRINCIPAL between", value1, value2, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayPrincipalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_PRINCIPAL not between", value1, value2, "payPrincipal");
			return (Criteria) this;
		}

		public Criteria andPayInterestIsNull() {
			addCriterion("PAY_INTEREST is null");
			return (Criteria) this;
		}

		public Criteria andPayInterestIsNotNull() {
			addCriterion("PAY_INTEREST is not null");
			return (Criteria) this;
		}

		public Criteria andPayInterestEqualTo(BigDecimal value) {
			addCriterion("PAY_INTEREST =", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestNotEqualTo(BigDecimal value) {
			addCriterion("PAY_INTEREST <>", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestGreaterThan(BigDecimal value) {
			addCriterion("PAY_INTEREST >", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_INTEREST >=", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestLessThan(BigDecimal value) {
			addCriterion("PAY_INTEREST <", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_INTEREST <=", value, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestIn(List<BigDecimal> values) {
			addCriterion("PAY_INTEREST in", values, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestNotIn(List<BigDecimal> values) {
			addCriterion("PAY_INTEREST not in", values, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_INTEREST between", value1, value2, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayInterestNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_INTEREST not between", value1, value2, "payInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestIsNull() {
			addCriterion("PAY_PUNITIVE_INTEREST is null");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestIsNotNull() {
			addCriterion("PAY_PUNITIVE_INTEREST is not null");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestEqualTo(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST =", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestNotEqualTo(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST <>", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestGreaterThan(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST >", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST >=", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestLessThan(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST <", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_PUNITIVE_INTEREST <=", value, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestIn(List<BigDecimal> values) {
			addCriterion("PAY_PUNITIVE_INTEREST in", values, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestNotIn(List<BigDecimal> values) {
			addCriterion("PAY_PUNITIVE_INTEREST not in", values, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_PUNITIVE_INTEREST between", value1, value2, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayPunitiveInterestNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_PUNITIVE_INTEREST not between", value1, value2, "payPunitiveInterest");
			return (Criteria) this;
		}

		public Criteria andPayAmountIsNull() {
			addCriterion("PAY_AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andPayAmountIsNotNull() {
			addCriterion("PAY_AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andPayAmountEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT =", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT <>", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountGreaterThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT >", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT >=", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountLessThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT <", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT <=", value, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT in", values, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT not in", values, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_AMOUNT between", value1, value2, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_AMOUNT not between", value1, value2, "payAmount");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumIsNull() {
			addCriterion("PAY_AMOUNT_SUM is null");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumIsNotNull() {
			addCriterion("PAY_AMOUNT_SUM is not null");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM =", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumNotEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM <>", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumGreaterThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM >", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM >=", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumLessThan(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM <", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("PAY_AMOUNT_SUM <=", value, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT_SUM in", values, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumNotIn(List<BigDecimal> values) {
			addCriterion("PAY_AMOUNT_SUM not in", values, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_AMOUNT_SUM between", value1, value2, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAmountSumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("PAY_AMOUNT_SUM not between", value1, value2, "payAmountSum");
			return (Criteria) this;
		}

		public Criteria andPayAcctIsNull() {
			addCriterion("PAY_ACCT is null");
			return (Criteria) this;
		}

		public Criteria andPayAcctIsNotNull() {
			addCriterion("PAY_ACCT is not null");
			return (Criteria) this;
		}

		public Criteria andPayAcctEqualTo(String value) {
			addCriterion("PAY_ACCT =", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctNotEqualTo(String value) {
			addCriterion("PAY_ACCT <>", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctGreaterThan(String value) {
			addCriterion("PAY_ACCT >", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctGreaterThanOrEqualTo(String value) {
			addCriterion("PAY_ACCT >=", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctLessThan(String value) {
			addCriterion("PAY_ACCT <", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctLessThanOrEqualTo(String value) {
			addCriterion("PAY_ACCT <=", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctLike(String value) {
			addCriterion("PAY_ACCT like", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctNotLike(String value) {
			addCriterion("PAY_ACCT not like", value, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctIn(List<String> values) {
			addCriterion("PAY_ACCT in", values, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctNotIn(List<String> values) {
			addCriterion("PAY_ACCT not in", values, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctBetween(String value1, String value2) {
			addCriterion("PAY_ACCT between", value1, value2, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayAcctNotBetween(String value1, String value2) {
			addCriterion("PAY_ACCT not between", value1, value2, "payAcct");
			return (Criteria) this;
		}

		public Criteria andPayManIsNull() {
			addCriterion("PAY_MAN is null");
			return (Criteria) this;
		}

		public Criteria andPayManIsNotNull() {
			addCriterion("PAY_MAN is not null");
			return (Criteria) this;
		}

		public Criteria andPayManEqualTo(String value) {
			addCriterion("PAY_MAN =", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManNotEqualTo(String value) {
			addCriterion("PAY_MAN <>", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManGreaterThan(String value) {
			addCriterion("PAY_MAN >", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManGreaterThanOrEqualTo(String value) {
			addCriterion("PAY_MAN >=", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManLessThan(String value) {
			addCriterion("PAY_MAN <", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManLessThanOrEqualTo(String value) {
			addCriterion("PAY_MAN <=", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManLike(String value) {
			addCriterion("PAY_MAN like", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManNotLike(String value) {
			addCriterion("PAY_MAN not like", value, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManIn(List<String> values) {
			addCriterion("PAY_MAN in", values, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManNotIn(List<String> values) {
			addCriterion("PAY_MAN not in", values, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManBetween(String value1, String value2) {
			addCriterion("PAY_MAN between", value1, value2, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayManNotBetween(String value1, String value2) {
			addCriterion("PAY_MAN not between", value1, value2, "payMan");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("PAY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("PAY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("PAY_TIME =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("PAY_TIME <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("PAY_TIME >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("PAY_TIME >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("PAY_TIME <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("PAY_TIME <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("PAY_TIME in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("PAY_TIME not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("PAY_TIME between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("PAY_TIME not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andOperIsNull() {
			addCriterion("OPER is null");
			return (Criteria) this;
		}

		public Criteria andOperIsNotNull() {
			addCriterion("OPER is not null");
			return (Criteria) this;
		}

		public Criteria andOperEqualTo(Long value) {
			addCriterion("OPER =", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotEqualTo(Long value) {
			addCriterion("OPER <>", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperGreaterThan(Long value) {
			addCriterion("OPER >", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperGreaterThanOrEqualTo(Long value) {
			addCriterion("OPER >=", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperLessThan(Long value) {
			addCriterion("OPER <", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperLessThanOrEqualTo(Long value) {
			addCriterion("OPER <=", value, "oper");
			return (Criteria) this;
		}

		public Criteria andOperIn(List<Long> values) {
			addCriterion("OPER in", values, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotIn(List<Long> values) {
			addCriterion("OPER not in", values, "oper");
			return (Criteria) this;
		}

		public Criteria andOperBetween(Long value1, Long value2) {
			addCriterion("OPER between", value1, value2, "oper");
			return (Criteria) this;
		}

		public Criteria andOperNotBetween(Long value1, Long value2) {
			addCriterion("OPER not between", value1, value2, "oper");
			return (Criteria) this;
		}

		public Criteria andOperTimeIsNull() {
			addCriterion("OPER_TIME is null");
			return (Criteria) this;
		}

		public Criteria andOperTimeIsNotNull() {
			addCriterion("OPER_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andOperTimeEqualTo(Date value) {
			addCriterion("OPER_TIME =", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotEqualTo(Date value) {
			addCriterion("OPER_TIME <>", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeGreaterThan(Date value) {
			addCriterion("OPER_TIME >", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("OPER_TIME >=", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeLessThan(Date value) {
			addCriterion("OPER_TIME <", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeLessThanOrEqualTo(Date value) {
			addCriterion("OPER_TIME <=", value, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeIn(List<Date> values) {
			addCriterion("OPER_TIME in", values, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotIn(List<Date> values) {
			addCriterion("OPER_TIME not in", values, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeBetween(Date value1, Date value2) {
			addCriterion("OPER_TIME between", value1, value2, "operTime");
			return (Criteria) this;
		}

		public Criteria andOperTimeNotBetween(Date value1, Date value2) {
			addCriterion("OPER_TIME not between", value1, value2, "operTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ml_pay_record
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ml_pay_record
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 29 21:10:43 GMT+08:00 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}