package com.wealth.miniloan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MlPayRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.RECORD_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private Long recordId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.LOAN_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private Long loanId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_PRINCIPAL
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private BigDecimal payPrincipal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private BigDecimal payInterest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_PUNITIVE_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private BigDecimal payPunitiveInterest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_AMOUNT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private BigDecimal payAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_AMOUNT_SUM
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private BigDecimal payAmountSum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_ACCT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private String payAcct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_MAN
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private String payMan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.PAY_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.OPER
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private Long oper;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ml_pay_record.OPER_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	private Date operTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.RECORD_ID
	 * @return  the value of ml_pay_record.RECORD_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Long getRecordId() {
		return recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.RECORD_ID
	 * @param recordId  the value for ml_pay_record.RECORD_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.LOAN_ID
	 * @return  the value of ml_pay_record.LOAN_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Long getLoanId() {
		return loanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.LOAN_ID
	 * @param loanId  the value for ml_pay_record.LOAN_ID
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setLoanId(Long loanId) {
		this.loanId = loanId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_PRINCIPAL
	 * @return  the value of ml_pay_record.PAY_PRINCIPAL
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public BigDecimal getPayPrincipal() {
		return payPrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_PRINCIPAL
	 * @param payPrincipal  the value for ml_pay_record.PAY_PRINCIPAL
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayPrincipal(BigDecimal payPrincipal) {
		this.payPrincipal = payPrincipal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_INTEREST
	 * @return  the value of ml_pay_record.PAY_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public BigDecimal getPayInterest() {
		return payInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_INTEREST
	 * @param payInterest  the value for ml_pay_record.PAY_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayInterest(BigDecimal payInterest) {
		this.payInterest = payInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_PUNITIVE_INTEREST
	 * @return  the value of ml_pay_record.PAY_PUNITIVE_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public BigDecimal getPayPunitiveInterest() {
		return payPunitiveInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_PUNITIVE_INTEREST
	 * @param payPunitiveInterest  the value for ml_pay_record.PAY_PUNITIVE_INTEREST
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayPunitiveInterest(BigDecimal payPunitiveInterest) {
		this.payPunitiveInterest = payPunitiveInterest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_AMOUNT
	 * @return  the value of ml_pay_record.PAY_AMOUNT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public BigDecimal getPayAmount() {
		return payAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_AMOUNT
	 * @param payAmount  the value for ml_pay_record.PAY_AMOUNT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayAmount(BigDecimal payAmount) {
		this.payAmount = payAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_AMOUNT_SUM
	 * @return  the value of ml_pay_record.PAY_AMOUNT_SUM
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public BigDecimal getPayAmountSum() {
		return payAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_AMOUNT_SUM
	 * @param payAmountSum  the value for ml_pay_record.PAY_AMOUNT_SUM
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayAmountSum(BigDecimal payAmountSum) {
		this.payAmountSum = payAmountSum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_ACCT
	 * @return  the value of ml_pay_record.PAY_ACCT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public String getPayAcct() {
		return payAcct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_ACCT
	 * @param payAcct  the value for ml_pay_record.PAY_ACCT
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayAcct(String payAcct) {
		this.payAcct = payAcct == null ? null : payAcct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_MAN
	 * @return  the value of ml_pay_record.PAY_MAN
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public String getPayMan() {
		return payMan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_MAN
	 * @param payMan  the value for ml_pay_record.PAY_MAN
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayMan(String payMan) {
		this.payMan = payMan == null ? null : payMan.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.PAY_TIME
	 * @return  the value of ml_pay_record.PAY_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.PAY_TIME
	 * @param payTime  the value for ml_pay_record.PAY_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.OPER
	 * @return  the value of ml_pay_record.OPER
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Long getOper() {
		return oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.OPER
	 * @param oper  the value for ml_pay_record.OPER
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setOper(Long oper) {
		this.oper = oper;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ml_pay_record.OPER_TIME
	 * @return  the value of ml_pay_record.OPER_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public Date getOperTime() {
		return operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ml_pay_record.OPER_TIME
	 * @param operTime  the value for ml_pay_record.OPER_TIME
	 * @mbggenerated  Sat Nov 01 17:05:46 CST 2014
	 */
	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}
}